bigcommerce/docs

CONTRIBUTING.md
docs/stencil-docs/reference-docs/front-matter-reference.mdx
docs/stencil-docs/storefront-customization/using-front-matter.mdx

Updates to status related to similar_by_views being disabled on the platform currently.
*  Contributing.md updated with latest repository url.
*  Added callouts to pages referencing the `similar_by_views` being currently disabled on BC platform and that no data will be returned.
Reduce requests to BC support asking why the `customers also viewed` functionality is not working.
Related to Merchant support ticket #07492972

(no ticket): [external] Stencil, clarify that similar_by_views property is inactive

---

reference/catalog/products_catalog.v3.yml

* Update limit from 50 to 250 across the metafield endpoints
* Correction: Corrected Metafield endpoint limits to reflect accurate limits from 50 to 250. 
[DEVDOCS-5319]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5319]: [revise] Catalog/Products/Metafields, Update platform limits across Metafield endpoints

---

reference/store_information.v2.yml

* from https://github.com/bigcommerce/api-specs/issue/1358
* update logo datatype
* file cleanup
* Update Store Information logo datatype
* https://github.com/bigcommerce/api-specs/issue/1358
ping {names}

ISSUE-1358: [update] Store Information, update logo datatype

---

reference/tax_provider.yml

* remove full refund for description of Adjust endpoint (Tax Provider API)
* add full refund for description of Void endpoint (Tax Provider API)
[DEVDOCS-5641]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5641 [update]: Tax Provider API, remove full refund from Adjust endpoint

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx

See [Issue 17](https://github.com/bigcommerce/docs/issues/17)
* 
ping {names}
[DEVDOCS-5718]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5718: [update] change back to node 18

---

docs/stencil-docs/installing-stencil-cli/node-sass.mdx

These commands are not recognized using the latest version of the stencil-cli. The command that works is `stencil scss-autofix`.
* Updated the autofix-scss commands since the listed commands do not work in  the latest version of the stencil cli
Fixed typos in the stencil cli autofix-scss commands
ping {names}

(no ticket): [external] node-sass, correct scss-autofix commands

---

reference/tax_rates_zones.v3.yml

* Merge in the override changes that revert the file to OAS 3.0.0
* Remove old callout artifacts
* Reconcile with recent changes
* 
ping @bc-andreadao
[SELFDEV-494]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-494: [update] Tax Rates & Zones, reconcile spec overrides

---

reference/tax_zone_check.v3.yml

Add documentation in api-specs repo for our new ZoneCheck endpoint
https://bigcommercecloud.atlassian.net/browse/TAX-1995
* Added new spec file for the `tax/zonecheck` endpoint
https://github.com/bigcommerce/api-proxy-java/pull/2659#issuecomment-1859527805
Specs match the response:
ping @bigcommerce/team-shipping 
[DEVDOCS-5714]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(tax): TAX-1995 Add specs for new TaxZone check endpoint

---

docs/api-docs/payments/payments-api-overview.mdx
reference/payments/process_payments.yml

* Added bank account instrument to payments API doc.
* Added Braintree ACH block to payments overview. 
* 
ping {names}
[PAYPAL-3377]: https://bigcommercecloud.atlassian.net/browse/PAYPAL-3377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(payment): PAYPAL-3377 Add support of braintree.ach in payments API

---

reference/catalog/product-modifiers_catalog.v3.yml
reference/catalog/product-variant-options_catalog.v3.yml
reference/catalog/products_catalog.v3.yml

* remove incorrect caveat about swatch defaults
* Removed an incorrect caveat about swatch defaults. It is possible to set a default value for swatch options and modifiers.
* [bigcommerce/api-specs issue-1468](https://github.com/bigcommerce/api-specs/issues/1468)
ping @bobbyshaw @kristinapototska

ISSUE-1468: [update] Catalog, remove caveat about swatch defaults

---

reference/orders.v2.oas2.yml

* Add the default PUT behavior for OrdersV2 in the endpoint description
* Does this need one if it's an omission?
ping @bc-vincent-zhao 
[DEVDOCS-5379]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5379]: [update] OrdersV2, Order/id/ PUT needs clarification about the default behavior in the description

---

reference/catalog/categories_catalog.v3.yml

Added some missing title fields to catalog categories API spec. 
These additions will allow for better type naming for code clients auto-generated from the spec. 
Changes types "InlineResponse200" to "CreateImageResponse"
and "InlineResponse2001" to "ProductSortOrder".
[PSE-896]: https://bigcommercecloud.atlassian.net/browse/PSE-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSE-896: [update] Catalog Categories, add some missing titles

---

reference/catalog/brands_catalog.v3.yml

Added some missing title fields to catalog brands API spec. 
These additions will allow for better type naming for code clients auto-generated from the spec. 
Changes types "InlineResponse200" to "BrandImageResponse"
[PSE-904]: https://bigcommercecloud.atlassian.net/browse/PSE-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSE-904:[update] Catalog Brands, add some missing titles

---

reference/settings.v3.yml
reference/store_information.v2.yml

* Store Information
* add storefront limits
* add detail to the rest of the schema
* Store Settings
* add schema title
* The [Get store information](/docs/rest-management/store-information) endpoint now returns information about storefront limits! The new data includes the number of active storefronts and the total number of storefronts, including inactive ones.
ping @njb and @bc-traciporter this one has release notes
[DEVDOCS-5756]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5756: [new] Store Information, add storefront limits

---

reference/orders.v2.oas2.yml

* #83
* change shipping_provider to anyOf to accommodate custom providers and support autogeneration
* add examples
* We've updated the shipping_provider property throughout the Orders V2 spec to allow arbitrary strings. This better indicates support for new and custom shipping providers, and improves API client autogeneration.
* #83
ping FYI @bc-andreadao @theromulans

ISSUE-83: [update] Orders V2, change shipping_provider to anyOf

---

docs/stencil-docs/reference-docs/front-matter-reference.mdx

* #79
* remove mistaken products value from category attributes example schema
* fix spacing
* We fixed an error in the category attributes schema in the Stencil frontmatter reference. Setting product limits should now be clearer!
* #79
ping @loganwoolf

ISSUE-79: [update] Stencil Frontmatter, fix category attributes schema

---

reference/catalog/product-variants_catalog.v3.yml

Added some missing title fields to catalog product-variants API spec. 
These additions will allow for better type naming for code clients 
Changes types "InlineResponse2007" to "MultiStatus"
[PSE-909]: https://bigcommercecloud.atlassian.net/browse/PSE-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSE-909: [update] Better return type for Mult-Status response

---

reference/webhooks.v3.yml

Remove empty `allOf` sections.
Moreover a lot of these schemas are unused so it is safe to merge. 
Rule: disallow empty `allOf`, `oneOf` sections
none

(no ticket): [update] Webhooks, remove empty allOf sections

---

docs/api-docs/apps/guide/apps-01-introduction.mdx
docs/api-docs/apps/guide/apps-02-types.mdx
docs/api-docs/apps/guide/apps-03-developing.mdx
docs/api-docs/apps/guide/apps-05-oauth.mdx
docs/api-docs/apps/guide/apps-06-callbacks.mdx
docs/api-docs/apps/guide/apps-07-users.mdx
docs/api-docs/apps/guide/apps-08-events.mdx
docs/api-docs/apps/guide/apps-09-ui.mdx
docs/api-docs/apps/guide/apps-10-buttons.mdx
docs/api-docs/apps/guide/apps-11-best-practices.mdx
docs/api-docs/apps/guide/apps-12-requirements.mdx
docs/api-docs/apps/guide/apps-13-publishing.mdx
docs/api-docs/channels/building-channel-apps.mdx
docs/api-docs/channels/channel-app-best-practices.mdx

Removes the initial sample app for channels that was created in 2019. That repo is now archived.
_Release note not needed_

SBD-955: [remove] legacy channel app references

---

reference/catalog/products_catalog.v3.yml

* Adding titles to response schema
These changes will make return types more readable for users using our docs to generate clients.
I am not 100% sure on the titles, I tried to use existing language but open to other ideas.
ping @bc-tgomez 
[PSE-911]: https://bigcommercecloud.atlassian.net/browse/PSE-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PSE-911: [update] Title schema for products v3 API docs

---

reference/catalog/products_catalog.v3.yml

- Update 207 response description
[DEVDOCS-5793]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5793: Catalog API, update 207 response description

---

archive/rest-catalog/custom-fields.v2.yml
reference/catalog/products_catalog.v3.yml

* Updated v3 custom-fields swagger scheme
* updated error messaging for custom fields;
* clarified info about limitation of 250 max allowed characters for the name and value in custom fields.
ping @bigcommerce/team-catalog

CATALOG-9219: [update] Catalog, update all Product Custom Fields endpoints

---

reference/carts.v3.yml
reference/catalog/brands_catalog.v3.yml
reference/catalog/categories_catalog.v3.yml
reference/catalog/product-variants_catalog.v3.yml
reference/catalog/products_catalog.v3.yml
reference/channels.v3.yml
reference/customers.v3.yml
reference/orders.v3.yml

* Rename `Get All Metafields` reference titles to be more relevant to the resource type being retrieved.
* The metafield endpoints in the reference will be more relevant to the resource being fetched, and there won't be duplicate names across different schemas.
ping @bigcommerce/dev-docs 
[DEVDOCS-5801]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5801: Fix wording for metafields endpoints

---

reference/catalog/products_catalog.v3.yml

* “date_last_imported“ field is added to the Product model
“date_last_imported“ field is added to the Product model. The field format is _nullable datetime string_ (e.g.: "2024-01-24T14:36:56+00:00”). The field is modifiable & filterable.
----
ping @bigcommerce/catalog-dt-php 
[CATALOG-8071]: https://bigcommercecloud.atlassian.net/browse/CATALOG-8071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(catalog): CATALOG-8071 Add date_last_imported to V3 API catalog/products

---

reference/settings.v3.yml

- Remove Channel ID query parameter from locale endpoints  
No changelog entry 
[DEVDOCS-5807]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5807 [new]: Settings API, remove Channel ID query parameter

---

reference/orders.v2.oas2.yml

- Correct the type for "external_order_id" query parameter in GET /v2/orders
ping @bigcommerce/team-orders @bc-traciporter 
[ORDERS-6095]: https://bigcommercecloud.atlassian.net/browse/ORDERS-6095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(orders): ORDERS-6095 correct the type for "external_order_id" query parameter in GET /v2/orders

---

reference/orders.v2.oas2.yml

Context: https://bigcommerce.slack.com/archives/C96P5T3J4/p1709383968237619
we have order_Resp https://github.com/bigcommerce/docs/blob/main/reference/orders.v2.oas2.yml#L2690
```
order_Resp:
title: order_Resp
description: Order object returned in responses.
allOf:
- $ref: '#/components/schemas/order_RespOnly'
- $ref: '#/components/schemas/order_Shared'
```
The below fields exists in both the `order_RespOnly` and `order_Shared`, so it leads to duplication problem in our [BC public API doc](https://developer.bigcommerce.com/docs/rest-management/orders#create-an-order) and error in the API client generator: 
- `billing_address`:  
- `default_currency_code`:
Remove the duplications of those fields in the `order_RespOnly` and `order_Shared`
- Fix a bug that show duplication of …

doc(orders): ORDERS-6248 avoid duplicated fields with "allOf" openapi schemas in Orders v2 API

---

reference/store_content.v2.yml

* Add note to indicate that blog posts default to draft status on create and update.
* clean up store_content.v2.yml
* We've updated the blog feature specification to note that the `is_published` field defaults to false on both POST and PUT. Pass `true` to avoid reverting the post to draft status. 
ping {names}
[DEVDOCS-5153]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5153: [update] Store Content, blog posts default to draft status

---

docs/stencil-docs/reference-docs/front-matter-reference.mdx

The documentation is correct now but I have been asked to make it very clear that you can add front matter to the custom directory.
See [PR 131](https://github.com/bigcommerce/docs/pull/131)
ping {names}
[DEVDOCS-5464]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added more clarification for custom folder

---

reference/themes.v3.yml

- Add `channel_id` as a query parameter for Activate a Theme endpoint
- Remove required flag from `which` field 
[DEVDOCS-5723]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5723 [update]: Themes API, add channel_id as a query parameter

---

docs/api-docs/storefront/graphql/graphql-api-overview.mdx

* Re-formatted the example GraphQL complexity limit error message to match what is actually returned: An `errors` array with a `message` property in the error object.
* Fixed incorrect formatting of the example error message for GraphQL complexity limits.

Fix for GraphQL complexity limit example error message

---

docs/api-docs/building-storefronts/nextjs-bigcommerce.mdx

- Added callout for Catalyst 
[DEVDOCS-5605]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5605 [revise]: Headless, add callout for Catalyst

---

reference/checkouts.v3.yml
reference/customers.v3.yml

Make state_or_province required in the Add Consignment to Checkout endpoint
Bug Fix
See DEVDOCS tickets for screenshots.
ping {names}
[DEVDOCS-5834]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-5833]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5834 [Update] make state_or_province required

---

reference/storefront_tokens.v3.yml

* BigCommerce currently allows sending two domains for CORS, API doc updated to change the limit from 1 to 2.
* Create GraphQL token API docs - updated the number of allowed domains for CORS to 2.
BigCommerce currently allows sending two domains, we get this error when we send more than 2 origins : "Allowed CORS origins list length should not be greater than 2".
[DEVDOCS-5767]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5767: Create a storefront token API allows 2 domains

---

reference/marketing.v2.yml

I just checked this endpoint and it returns 201 instead of 200
```shell
curl --verbose --request POST \
--url "https://api.bigcommerce.com/stores/$HASH/v2/gift_certificates" \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header "X-Auth-Token: $TOKEN" \
--data '{"to_name":"John Doe","to_email":"johndoe@example.com","from_name":"Jane Doe","from_email":"janedoe@example.com","amount":"11","balance":"0","purchase_date":"Mon, 19 Jan 1970 07:21:46 CST","expiry_date":"Tue, 20 Jan 1970 08:45:38 CST","customer_id":5,"template":"celebration.html","message":"Congratulations!","code":"ABC-5N4-C7M-S78","status":"active","currency_code":"PLN"}'
```

[No-Ticket]: [revise] MarketingV2, Fix status code in marketing.v2.yml

---

docs/api-docs/storefront/graphql/graphql-faceted-textual-search.mdx

- Clarified how API handles price sort order
[DEVDOCS-5168]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5168 [revise]: GQL SF API Faceted Search, clarify price sort order

---

reference/checkouts.v3.yml

Updated checkout discount endpoint
V3/Discounts API can now be used to add item-level discount in addition to cart level discount
Initial PR: [PR 1517](https://github.com/bigcommerce/api-specs/pull/1517)
[Checkout-7756](https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7756)
ping @valentindellangela and @bc-charlesho for review
[DEVDOCS-5646]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5646 [update] Checkouts, changes to discounts

---

docs/api-docs/users/overview.mdx

Jira: [ANA-4629](https://bigcommercecloud.atlassian.net/browse/ANA-4629)
* Updating the AddUserToStore documentation to reflect the security patch that the IAM team tackled as part of ANA-4629. The vulnerability there was that it was possible for attackers to enumerate through user ID's and retrieve all the emails of users throughout the platform if they were successful in using an ID that belongs to someone. The IAM team recommends that we instead use email as the identifier for users as part of this specific mutation, however we are still allowing for a set of accounts that have existing Users API tokens to continue using the original API contract as before.
* 
ping {names}
[ANA-4629]: https://bigcommercecloud.atlassian.net/browse/ANA-4629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

feat(iam): ANA-4629 Update AddUserToStore docs to reflect security patch

---

reference/customers.v3.yml

Fixes #212
Changes mapping value from #/components/schemas/PaypalAccountInstrument to #/components/schemas/PayPalAccountInstrument in response for the Get Stored Instrument API operation in the Customers V3 OpenAPI spec
Updates OpenAPI spec: Fixes letter case in response mapping for the `PayPalAccountInstrument` when querying the V3 customers API for Stored Instruments
n/a
[DEVDOCS-5880]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(customers): Fix letter case in response mapping for the Get Stored Instrument API operation

---

docs/api-docs/provider-apis/tax/overview.mdx

On the back of a recent incident we identified there was an opportunity to speak more about performance and our timeout expectations in our Tax Provider API documentation.
Here we are introducing a new section on this topic. Further comments inline.

TAX-2050: Add performance/timeout section to tax provider API documentation

---

docs/api-docs/webhooks/webhook-events.mdx

Added deliveryException hooks to webhook events
The newly-released delivery exception webhooks alert users of delivery issues at their primary delivery destination.
ping {names}
[DEVDOCS-5856]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5856: [update] added deliveryException hooks to webhook events

---

docs/api-docs/channels/channel-webhooks.mdx
reference/catalog/products_catalog.v3.yml

* Removed dot from the end of the `PUT Create Products Category Assignments` summary
* Updated link to category assignments on the Channel Webhooks page
These changes with broken link (because of dot sign at the end):
https://github.com/bigcommerce/docs/assets/79109064/49baa6df-354d-4c18-9ba7-a3915e844429
Not sure what to put here, need help from Dev Docs team.
Bug Fix

fix category assignments link

---

docs/api-docs/storefront/scripts-overview.mdx
reference/scripts.v3.yml

- update Scripts yml file to include hash property
- update Scripts doc to include info about how BC handles integrity hashes
* The newly-released SRI hash feature is now available to use. Now, you’ll be able to add SRI hashes to external SRC scripts.
[DEVDOCS-5796]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5796 [new]: Scripts API, add integrity hash

---

reference/orders.v3.yml

* Add note describing the logical relationship between the amounts used in the /refunds_quotes endpoint and the /refunds endpoint.
* 
ping @bc-vincent-zhao 
[DEVDOCS-5829]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5829]: [revise] OrdersV3, Update notes for /refund_quotes endpoint

---

reference/carts.v3.yml

Removed "Redirect URLs can be generated only from carts that were created using the REST Management API."
Bug Fix
* 
ping {names}
[DEVDOCS-5850]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5850: [update] removed incorrect statement

---

reference/carts.v3.yml
reference/catalog/brands_catalog.v3.yml
reference/catalog/categories_catalog.v3.yml
reference/catalog/product-variants_catalog.v3.yml
reference/catalog/products_catalog.v3.yml
reference/channels.v3.yml
reference/customers.v3.yml
reference/orders.v3.yml

- add include_fields query parameter on Batch Metafields
This PR is related to [PR 305](https://github.com/bigcommerce/api-specs-ssot/pull/305)
Examples:
* We're happy to announce the `include_fields` query parameter on batch metafields, which can help you query specific enum fields.
[DEVDOCS-5839]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5839 [update]: Batch Metafields, add include_fields query parameter

---

reference/checkouts.sf.yml

This PR fixes the content in checkout consignment "Create a consignment" rendering incorrectly.
* Removed some leading indents causing the render component to render as a code block instead of the intended behavior
* n/a
ping @slsriehl 
[SELFDEV-166]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] Checkout Consignments: Content is not wrapping properly

---

reference/orders.v2.oas2.yml

* Remove UPSOnline from the list of shippers
*  Create an order shipment no longer supports UPSOnline as a shipper
ping {names}
[DEVDOCS-5931]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5931]: [update] Ordersv2, Remove outdated shipper from create order shipment list

---

docs/api-docs/customers/customers-subscribers-overview.mdx

* Added examples of POST/PUT requests for subscribers
* Added information around the importance of `consents` determining whether a subscriber has opted in or not
Currently there is ambiguity around what it means to be a subscriber or not. When a shopper is created during checkout, regardless a subscriber will be created (however they may not be opted in, a record exists regardless).
N/A
ping @bc-tgomez @bigcommerce/team-customers 
[CUST-2597]: https://bigcommercecloud.atlassian.net/browse/CUST-2597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(customers): CUST-2597 Customers-Subscribers overview page

---

.github/actions/retext-style-guide/action.yml
.github/actions/retext-style-guide/entrypoint.sh
.github/workflows/retext-style-guide.yml

Before: 
- When I make a commit, Reviewdog (re)comments on all the lines in the PR 
After:
- When I make a commit, Reviewdog comments on only the lines included in the commit 
[DEVDOCS-5627]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5627 [update]: Remark linter 

---

reference/price_lists.v3.yml

* The name:like parameter is documented to accept an array, however it can only accept a string for price lists.
* Provide accurate documentation as to what data type the name:like parameter accepts for Price Lists.
Confirmed by pricing team here:
https://bigcommerce.slack.com/archives/C05DH8JCESU/p1713971423881579
[DEVDOCS-5907]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5907: [update] Pricing, change name:like from csv array to string

---

docs/api-docs/customers/customers-subscribers-overview.mdx

* Added examples of POST/PUT requests for subscribers
* Added information around the importance of `consents` determining whether a subscriber has opted in or not
Currently there is ambiguity around what it means to be a subscriber or not. When a shopper is created during checkout, regardless a subscriber will be created (however they may not be opted in, a record exists regardless).
Related: doc(customers): CUST-2597 Customers-Subscribers overview page (#273)
ping @bc-tgomez @bigcommerce/team-customers @slsriehl 
[CUST-2597]:
https://bigcommercecloud.atlassian.net/browse/CUST-2597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
* 
* 
ping {names}
[DEVDOCS-5945]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5945?atlOrigin=eyJpIjoiNWRkNT …

[DEVDOCS-5945]: [update] Customers, Update API examples and add contextual info

---

reference/catalog/product-variants_catalog.v3.yml

* #280
* #281
* Reorder fields in the several product variant metafields responses
* Populate response body by removing required and readOnly fields from response schema
* 
ping @atensoftware @bc-tgomez

ISSUE-280 + ISSUE-281: [update] Product variant metafields, reorder fields + populate response example

---

reference/tax_provider.yml

- Add `fee` to tax item types.
No need for release notes, minor additive change that reflects an adjustment from some months ago.
Nope.

No ticket: Tax Provider API, add `fee` tax item type to `tax_item` types

---

docs/stencil-docs/localization/localizing-stores.mdx
docs/stencil-docs/localization/multi-language-checkout.mdx

- Add Japanese as a supported language for your Stencil storefront content. 
We are excited to announce Japanese language support. Now, BigCommerce's Cornerstone Stencil theme supports uneditable strings in Japanese.
@bigcommerce/team-localization 
[DEVDOCS-5890]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5890 [new]: Stencil theme, add Japanese language

---

reference/shipping.v2.yml

Change response code
Fixed a bug in the /v2/shipping/zones. Now the response code is 201 instead of 200
-

Fix response code for createShippingZones operation

---

reference/customers.v3.yml

* Add `origin_channel_ids` to the list of read only fields
* Added origin_channel_id to the list of read-only fields in the Customers V3 API. This field is set upon customer creation and cannot be updated afterward.
ping @
[DEVDOCS-5715]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5715]: [revise] Customers V3, Add origin_channel_id to the list of read only fields

---

docs/api-docs/tax/tax-settings.mdx
reference/tax_settings.v3.yml

- Add document submission strategy field
* We're happy to announce the [Tax Settings API's](https://developer.bigcommerce.com/docs/rest-management/tax-settings) new `document_submission_strategy` field, which lets you choose when tax documents are submitted to third-party tax providers.
[DEVDOCS-5929]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5929 [new]: Tax Settings API, add document submission strategy field

---

reference/channels.v3.yml

- Add a note to Channel Listings API that it's intended for non-storefront channels  
* N / A
[DEVDOCS-5939]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5939 [update]: Channel listings, add usage note

---

reference/sites.v3.yml

This PR changes the request body of PUT site's routes to an array of objects, as pointed out by the SELFDEV-626 submitter. 
> Furthermore, the code sample for "Update a Site's Routes" is incorrect. Since it's a bulk update for all possible Routes, it should be wrapped in an array:
> ```
> [{
> "id": 0,
> "type": "product",
> "matching": "5",
> "route": "/my-amazing-product"
> }]
> ```
> Attempting to run the code sample presently documented will result in this error:
> 
> ```
> "status": 422,
> "title": "The request payload has to be a JSON array for the endpoint"
> ```
[SELFDEV-626]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-626 Change PUT site's routes body to array

---

reference/price_lists.v3.yml

Update schemas for pricelist bulk tiers to cover that `null` may be returned when there is no upper limit on the quantity for a given tier.
* Update schemas for pricelist bulk tiers to cover that `null` may be returned when there is no upper limit on the quantity for a given tier.
* Unrelatedly, add a `'` to "this tiers pricing" since it's a possessive rather than a plural.
* Clarified documentation for pricelist bulk tier pricing to explain tiers with no upper quantity limit.
Nope 😄

Update bulk pricing tiers documentation to cover `null` case

---

docs/storefront/graphql/customers.mdx

* Mention password complexity requirements that developers can use to validate passwords when registering / changing / resetting a customer's password
* The GraphQL Storefront API's newly-released [`CustomersSettings` node](https://developer.bigcommerce.com/graphql-storefront/reference#definition-CustomersSettings) has password complexity requirements that are now available. Now, when you register, update, or reset a customer's password, you’ll be able to validate it before submitting the customer's desired password to the BigCommerce Platform.
This PR relates to [PR 3054](https://github.com/bigcommerce/storefront/pull/3054) (editing schema descriptions)
To prevent broken links, this PR should be merged only after the node shows up on …

DEVDOCS-5971 [new]: GQL Storefront API / Customers, add password complexity requirements

---

docs/store-operations/catalog/graphql-admin/product-basic-info.mdx
docs/store-operations/catalog/msf-international-enhancements.mdx

P&E team needs the doc changes temporarily  reverted
* Revert Admin GQL API's custom fields, from [PR 347](https://github.com/bigcommerce/docs/pull/347), under P&E's discretion 
Goes hand in hand with [PR 946](https://github.com/bigcommerce/developer-center/pull/946)
[DEVDOCS-5957]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5957: Revert Admin GQL API's custom fields

---

reference/themes.v3.yml

Replacing all pagination objects with empty meta object (copied from email_templates.v3.yml)
* Removed all pagination objects and replaced them with empty meta object (copied from email_templates.v3.yml)
* Removed pagination object from [GET All Themes API call](https://developer.bigcommerce.com/docs/rest-content/themes#get-all-themes)
[DEVDOCS-6010]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-6010] Remove pagination object for Themes API

---

reference/webhooks.v3.yml

* Remove 'events' endpoint from documentation because of endpoint removing
* The endpoint in a process of removal. Need to remove all mentioning from documentation as well
ping {names}
[PAPI-2240]: https://bigcommercecloud.atlassian.net/browse/PAPI-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PAPI-2240: remove events endpoint from webhooks doc

---

docs/start/authentication/graphql-storefront.mdx
docs/storefront/graphql/index.mdx
reference/storefront_tokens.v3.yml

* Update reference & docs to mention that GQL Storefront API token & Customer Impersonation Tokens can be created for multiple channels
* We're happy to announce that you can now create [GraphQL Storefront API Tokens](https://developer.bigcommerce.com/docs/rest-authentication/tokens) that are valid for multiple channels. For more information, see [Create a Storefront API token](https://developer.bigcommerce.com/docs/rest-authentication/tokens#create-a-token) and [Create a Customer Impersonation Token](https://developer.bigcommerce.com/docs/rest-authentication/tokens/customer-impersonation-token#create-a-token).
[DEVDOCS-5999]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5999 [new]: GQL SF API, GQL token multiple channels

---

docs/integrations/apps/guide/auth.mdx
docs/integrations/apps/guide/types.mdx
docs/start/authentication/api-accounts.mdx

* Edit wording to include that authorized users (not just store owners) can manage API accounts
* We're happy to announce [X feature], which can help you  [perform Y action].
[DEVDOCS-4695]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4695 [new]: Store-level API accounts, add authorized users

---

reference/checkouts.v3.yml

The API reference for deleting a Consignment contains a note that deleting a checkout's last consignment removes the cart from its assigned customer.  This has been tested and found to be inaccurate, and Valentin Dellangela verified it should be removed.

Remove inaccurate note about deleting consignment unassociated a cart from a customer

---

reference/tax_provider.yml

* Adjust description of the `TaxQuote::id` field to describe that we also accept external ID values.
* Also describe how this value is used with adjust and void requests.
* Bonus: adjust remaining outlier casing concerns for "Tax Provider" => "tax provider".
Based on tax partner feedback and a significant confusion internally.
* Clarify accepted Tax Provider API quote ID values and usages.

Update description of TaxQuote::id

---

reference/channels.v3.yml

* Indicate that Update a channel does not support restoring a channel to `prelaunch` status.
* Fixed a bug to indicate that the Update a channel endpoint does not support restoring a channel to `prelaunch` status.
ping FYI @bc-tgomez
thanks @mattcoy-arcticleaf!

(no ticket): Channels feature, update allowed PUT statuses

---

docs/store-operations/catalog/graphql-admin/product-basic-info.mdx
docs/store-operations/catalog/msf-international-enhancements.mdx

P&E changes are done, asked to put doc back up 
Reverts bigcommerce/docs#371
[DEVDOCS-5957]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "DEVDOCS-5957: Revert Admin GQL API's custom fields"

---

docs/integrations/tax.mdx

* Set context of the intention of the Tax Provider API request model supporting required inputs for standard tax requests.
* Add advice on obtaining additional data that is not part of the Tax Provider API request model.
* Add guidance on Tax Properties, relating to performance and the topic of "additional data".
* Adjust `e.g.` to `e.g.,` as advised.
* Added guidance on how to best achieve a performant solution with the Tax Provider API.
[TAX-2153]: https://bigcommercecloud.atlassian.net/browse/TAX-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TAX-2153 [new]: Tax Provider API, add performance guidance

---

reference/checkouts.v3.yml

* 
* The newly-released `comparison_price` and `extended_comparison_price` fields are now available to use. Now, you’ll be able to identify the price of a single or line item (product x quantity) used for strike-through.
* 
ping {names}
[DEVDOCS-6045]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6045: [update]added comparison_price and extended_comparison_price

---

reference/catalog/products_catalog.v3.yml

Made changes based on my testing.
Outstanding issues:
1. The `is_featured` query parameter does not work as documented. Entering "1" or "true" does not work.
2. What field does the query parameter `inventory_low` related to? Is this the same as `inventory_warning_level`.
3. What field does the query paramter `out_of_stock` related to?
4. The values for the `keyword_context` query parameter give the same result.
5. What are the accepted values for the `status` query parameter?
6. Missing `reviews` and `parent_relations` from the Create a product response body.
* 
ping {names}
[DEVDOCS-6024]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6024: [TEST SPEC] changes from testing this endpoint

---

reference/sites.v3.yml

[No ticket]
Currently, the URLs for Get a Site Certificate & Upsert a Site Certificate don't work in the browser (due to the slash in the URL) (e.g. clicking on the sidebar menu doesn't help you navigate the page) 
1. `/docs/rest-management/sites/site-certificate#get-a-sites-ssl/tls-certificate-information` 
2. `/docs/rest-management/sites/site-certificate#upsert-a-sites-ssl/tls-certificate-information`
This PR changes the URLs:
1. `#get-a-sites-ssl/tls-certificate-information` becomes `#get-a-sites-ssl-tls-certificate-information`
2. `#upsert-a-sites-ssl/tls-certificate-information` becomes `#upsert-a-sites-ssl-tls-certificate-information`
N / A
N / A

[No ticket]: fix URL for site certificates

---

reference/customers.v2.yml

Minor formatting on `date_modified:max`
*  Extra ` removed in field `date_modified:max`
*  From
*  To
*

Update formatting field `date_modified:max` in customers.v2.yml

---

reference/carts.sf.yml
reference/carts.v3.yml
reference/checkouts.sf.yml
reference/checkouts.v3.yml

* Added `version` field to the request and response payload of the Storefront and Management REST Cart and Checkout API.
* Added a description explaining that this field can be used to enable optimistic concurrency control to prevent lost updates caused by concurrent updates.
We are happy to announce that the Cart and Checkout API now supports optimistic concurrency control. This feature helps prevent lost updates caused by concurrent requests overriding changes made by others. If the `version` number provided by an API client does not match the version on the server, the request will be rejected, allowing the client to handle the error accordingly.
ping @bigcommerce/dev-docs @bigcommerce/team-checkout 
[DEVDOCS-6022]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6022?atlOrigin=ey …

DEVDOCS-6022: Update cart/checkout API with information on concurrency control

---

reference/orders.v2.oas2.yml

*  Correct behaviour for orders PUT. Old description implied discounts are wiped on the whole order when in reality we only wipe discounts off the line items changed in the request.
None

docs(orders): ORDERS-6461 clarify PUT discounts behaviour

---

reference/carts.sf.yml
reference/carts.v3.yml
reference/checkouts.sf.yml
reference/checkouts.v3.yml

* Add `example` to `version` field for cart/checkout API. Otherwise, it shows up as `version: 0`, which is an invalid value.
N/A
Related PR: https://github.com/bigcommerce/docs/pull/439
ping @bigcommerce/dev-docs 
[DEVDOCS-6022]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6022: Add example value to version field for cart/checkout API

---

docs/b2b-edition/specs/api-v2/openAPI.yaml

Updated the B2B v2 APIs yaml spec with deprecation notices.
Now that the v3 B2B APIs are widely released, we've deprecated our set of v2 B2B endpoints.

Add deprecation notice to v2 B2B API endpoints (yaml)

---

reference/catalog/category-trees_catalog.v3.yml

* remove "readOnly" property from "category_id" schema
* No release note required
ping @NataliiaNefodova 
[CATALOG-10408]: https://bigcommercecloud.atlassian.net/browse/CATALOG-10408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CATALOG-10408: [update] Categories: fix of schema

---

reference/catalog/products_catalog.v3.yml

- Removed `product _id` from the Product Review response body endpoints. 
- Added `owner_client_id` to the Product Metafield response bodies
- Added examples for the Create Product Review request body endpoint.
* 
ping {names}
[DEVDOCS-6024]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6024 [TEST-SPEC]: updated per review

---

reference/orders.v3.yml

Update swagger file of the Refund API to support product refund deductions (adjustment)
* New field `adjustments` in request body of `POST /orders/{order_id}/payment_actions/refund_quotes` and `POST 
/orders/{order_id}/payment_actions/refunds`, and in  the response of `GET /orders/{order_id}/payment_actions/refunds`
* 
PROJECT-5156
[ORDERS-6254]: https://bigcommercecloud.atlassian.net/browse/ORDERS-6254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(orders): ORDERS-6254 support product refund deduction (adjustment) in Refund API

---

reference/store_information.v2.yml

Relevant slack conversation https://bigcommerce.slack.com/archives/C011NMGSUE9/p1723843420293349
- add `country_code` & `favicon_url` into schema for Get Store Information endpoint
N / A

DEVDOCS-6025 [update]: Store Information, add country_code & favicon_url into schema

---

reference/inventory.v3.yml

Relevant slack conversation https://bigcommerce.slack.com/archives/C05HK588YMN/p1723872133959149
* Add `sku_id` field to the response for Get Inventory at Locations endpoint
- Updated Get Inventory at Locations endpoint response body to have the `sku_id` field
@bigcommerce/team-inventory 

DEVDOCS-6025 [new]: Inventory API, add `sku_id` field

---

docs/storefront/stencil/cli/options-and-commands.mdx

See [ISSUE-467](https://github.com/bigcommerce/docs/issues/467).
* Stencil CLI allows a tunnel option. This tunnel option now contains a  password field implemented by the tunnel provider  to prevent abuse by malicious parties. 
ping {names}

ISSUE-467: [update] tunnel definition

---

docs/b2b-edition/about/index.mdx

* Updated links in the B2B overview section to point to developer center docs instead of Stoplight.
* Removed out of date blurb about Bundle B2B endpoints being seen, since we've already moved them to sit within a bigcommerce.com endpoint
* B2B Edition's API reference documentation has now been moved into our Developer Center, to provide a faster, more consistent experience for developers creating future B2B experiences. If you run into anything that can be improved, let us know!
ping @bigcommerce/dev-docs

Update references in B2B API overview to point to DevCenter references

---

reference/orders.v3.yml

There were 2 `date_created` fields in the response ([line 1786](https://github.com/bigcommerce/docs/pull/479/files#diff-9ead9bf906bd7b06c5133a2a772bc9c0495649ea31de58edf24e9ce085fb6569L1786) & [line 1845](https://github.com/bigcommerce/docs/pull/479/files#diff-9ead9bf906bd7b06c5133a2a772bc9c0495649ea31de58edf24e9ce085fb6569R1845)). Line 1845 has a better description, so this PR removes line 1786. 
N / A
Continuation of [PR 453](https://github.com/bigcommerce/docs/pull/453) where the description for `date_created` was changed

DEVDOCS-6025 [update]: Order Transactions, remove duplicate field

---

reference/store_information.v2.yml

* Added infrastructure_region to V2 Store API
The Store Information API now includes the `infrastructure_region` of the store so you can determine where the store is hosted geographically. This is helpful when you are deploying supporting infrastructure for the store so you can deploy it nearby (or in the same GCP region) to minimize latency.
[DEVDOCS-6100]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add infrastructure_region to V2 Store API

---

reference/carts.v3.yml
reference/checkouts.v3.yml

Added new field to physical and digital products. (added_by_promotion)
We recently exposed the added_by_promotion field in the v3 cart and checkout endpoints. 
ping {names}
[DEVDOCS-6098]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6098: [update] added_by_promotion field

---

docs/storefront/stencil/themes/foundations/react.mdx

* Updated the Babel plugin dependency that's recommended in the React foundation doc for Stencil, since it has moved into a new package since the doc was original created
* Stencil React foundation doc has been updated to work with the latest Babel plugin packages. Now the guidance works for React 18.

Update babel dependency in stencil react foundation doc

---

reference/shipping.v2.yml

is_fallback is used when advanced shipping rules (ShipperHQ) is unavailable. This change clarifies the role of fallback shipping methods.
* Update the documentation of the is_fallback property of shipping methods
The meaning of the is_fallback property of shipping methods has been clarified.

Clarify the role of is_fallback in shipping methods API

---

reference/orders.v2.oas2.yml

* Added `is_deleted` flag to order response attributes for [POST](https://developer.bigcommerce.com/docs/rest-management/orders#create-an-order), [PUT](https://developer.bigcommerce.com/docs/rest-management/orders#update-an-order), [GET ](https://developer.bigcommerce.com/docs/rest-management/orders#get-an-order)and[ GET all](https://developer.bigcommerce.com/docs/rest-management/orders#get-all-orders) calls
* Response body attributes map to order_RespOnly YAML object
* Documentation for `is_deleted` flag in V2 Orders API
*Twined with DEVDOCS-6007 - Investigate missing `is_deleted` parameter/attribute in Orders documentation
[DEVDOCS-6006]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

[DEVDOCS-6006] Document is_deleted flag for Orders

---

reference/carts.sf.yml
reference/carts.v3.yml
reference/checkouts.sf.yml
reference/checkouts.v3.yml

* Clarify the meaning of `version` field in the request/response of cart/checkout API so developers know what it can be used for.
N/A
ping @bigcommerce/team-checkout 
[DEVDOCS-6104]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6104: Clarify the meaning of version field in the request/response of cart/checkout API

---

reference/customers.v3.yml

* Addition of `trigger_account_created_notification` as a request parameter for Customer [POST](https://developer.bigcommerce.com/docs/rest-management/customers#create-customers)
* Addition of `trigger_account_created_notification` as a request parameter for Customer [POST](https://developer.bigcommerce.com/docs/rest-management/customers#create-customers)
https://bigcommercecloud.atlassian.net/browse/PROJECT-6641
ping @bc-tgomez @bigcommerce/team-customers 
[CUST-3450]: https://bigcommercecloud.atlassian.net/browse/CUST-3450

doc(customers): CUST-3450 Add account created notification to v3 customers POST endpoint

---

docs/integrations/channels/guide/storefronts.mdx
reference/channels.v3.yml

* Add `localization` to protected UI section (Channel Menus endpoint)
We're happy to announce that `localization` settings are now a [protected UI section](https://developer.bigcommerce.com/docs/integrations/channels/guide/storefronts#protected-ui-sections) when you [create a channel menu](https://developer.bigcommerce.com/docs/rest-management/channels/menus#create-channel-menus).
@bigcommerce/team-multi-storefront 
[DEVDOCS-6099]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6099 [new]: Channel Menus, add localization into protected UI section

---

docs/integrations/webhooks/events/index.mdx

* Clarified statement about custom fields (`store/product/updated` webhook triggers only for the channel locale, not the global store)
N / A
@bigcommerce/team-multi-storefront 
[DEVDOCS-6105]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6105 [revise]: MSF International Enhancements, clarify custom fields

---

reference/catalog/brands_catalog.v3.yml
reference/catalog/categories_catalog.v3.yml
reference/catalog/product-modifiers_catalog.v3.yml
reference/catalog/product-variants_catalog.v3.yml
reference/catalog/products_catalog.v3.yml

Added new contentType for the image endpoints
Bug Fix: corrected invalid Content-Type for image upload endpoints
ping {names}
[DEVDOCS-5966]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5966: [update] correct contentType

---

reference/checkouts.sf.yml
reference/inventory.v3.yml

Relevant slack conversation https://bigcommerce.slack.com/archives/C0WC9CSJX/p1724366031941559
Update schema for Storefront API's Checkout endpoints
- added in missing fields (see the above slack conversation)
- updated the examples to use those fields
The all the endpoints for Storefront Checkout have the same response (now reference the same response & example)
Updated the schema for the Storefront Checkout endpoints

DEVDOCS-6025 [update]: Storefront Checkouts, update response schema

---

docs/integrations/channels/guide/storefronts.mdx
reference/channels.v3.yml

- Updated the protected UI section and Channels API reference to include settings for: Overview, Script Manager, Payments, Checkout, Web pages, and Data solutions.
* We're happy to announce that we've added the following [protected UI sections](https://developer.bigcommerce.com/docs/integrations/channels/guide/storefronts#protected-ui-sections) when you build a storefront channel. You can now include these settings when you [create a channel menu](https://developer.bigcommerce.com/docs/rest-management/channels/menus#create-channel-menus): Overview, Script Manager, Payments, Checkout, Web pages, Data solutions. 
@bigcommerce/team-multi-storefront 
[DEVDOCS-6114]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

DEVDOC-6114 [update]: Channel Menus, add UI sections

---

reference/form_fields.sf.yml

Relevant slack conversation https://bigcommerce.slack.com/archives/C9LNQDWKX/p1724860197700219
*  add `requirements` field for password field types
Updated Storefront Form Fields API Spec

DEVDOCS-6025: SF Form Fields, add requirements field for password field

---

reference/catalog/category-trees_catalog.v3.yml

Updated the descriptions for parent_id and tree_id.
bug fix:
Clarified the parent_id and tree_id descriptions for creating a top level category
<--
Examples:
* The newly-released [X feature] is now available to use. Now, you’ll be able to [perform Y action].
* We're happy to announce [X feature], which can help you  [perform Y action].
* [X feature] helps you to create [Y response] using the [Z query parameter]. Now, you can deliver [ex, localized shopping experiences for your customers].
* Fixed a bug in the [X endpoint]. Now the [Y field] will appear when you click [Z option]. -->
* 
ping {names}
[DEVDOCS-6038]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6038: [update] update parent_id & tree_id definitions

---

docs/b2b-edition/specs/api-v3/company/company.yaml

- Moved over B2B endpoints for Company Attachments that launched since the initial docs transfer into our dev center
- Improved some of the descriptions in the spec
- Removed unnecessary x-stoplight references
ping @bigcommerce/dev-docs-team @bigcommerce/team-b2b

Add company attachment endpoints to B2B Edition API specs

---

reference/orders.v2.oas2.yml

https://bigcommercecloud.atlassian.net/browse/ORDERS-6362
* Added  is_tax_inclusive_pricing field in orders response
Swagger Proof:
https://github.com/user-attachments/assets/86560ebf-3fc7-482d-93b3-4190699b8c96

ORDERS-6362: [add] is_tax_inclusive_pricing field in orders response

---

docs/storefront/stencil/themes/context/object-reference/schemas/settings.yml

added deprecated tags to the settings theme object
The following stencil attribute fields are deprecated:
- settings.request.is_crawler
- 
- settings.request.user_agent
- 
- settings.client_ip_address
- 
- settings.region_code
ping {names}
[DEVDOCS-6042]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6042: [update] add deprecated tag

---

reference/orders.v2.oas2.yml

https://bigcommercecloud.atlassian.net/browse/ORDERS-6362
* Added  is_tax_inclusive_pricing field in orders response
Swagger Proof:
https://github.com/user-attachments/assets/86560ebf-3fc7-482d-93b3-4190699b8c96

ORDERS-6362: [add] is_tax_inclusive_pricing field in orders response 

---

.github/CODEOWNERS

* In order to ensure that public documentation remains up-to-date with development, the Catalog and Multi-Storefront teams want to have more visibility over the updating process. This includes introducing code ownership through the CODEOWNERS file, allowing for better visibility and control over changes to documentation.

Update MSF and Catalog ownership

---

docs/b2b-edition/specs/api-v3/invoice-management.yaml

This enables the specs to be organized under "Invoice Management" in the dev center. Once this is merged and devcenter updates, we can remove the separate invoice, payment, and receipt files.

Combine B2B invoice, payments, and receipt specs

---

reference/orders.v2.oas2.yml

Copied existing content for `order_source` attribute to show as request param for POST/PUT requests.
* Addition of `order_source` as a request parameter for Order [POST](https://developer.bigcommerce.com/docs/rest-management/orders#create-an-order)/[PUT ](https://developer.bigcommerce.com/docs/rest-management/orders#update-an-order) requests.
* Added in order_Put an order_Shared YAML objects.
* Addition of `order_source` as a request parameter for Order [POST](https://developer.bigcommerce.com/docs/rest-management/orders#create-an-order)/[PUT ](https://developer.bigcommerce.com/docs/rest-management/orders#update-an-order) requests.
* Twined with DEVDOCS-6009: Re-work of order_source parameter description
[DEVDOCS-6008]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6008?atlOrigin=e …

Add copy of order_source for POST/PUT request params

---

reference/customers.v3.yml

deprecated the customer form fields endpoint
The Upsert Customer Form Field Values endpoint is deprecated. Use [Update a Customer Address](/docs/rest-management/customers/addresses#update-a-customer-address) and [Update Customers](/docs/rest-management/customers#update-customers) endpoints instead.
ping {names}
[DEVDOCS-6111]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6111: [update] deprecate upsert form fields

---

CONTRIBUTING.md

These links go to placeholders. There is no information, therefore, removing them. 
N/A
ping {names}
[DEVDOCS-6077]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6077: [update] remove style guide references

---

docs/b2b-edition/specs/api-v3/address/address.yaml
docs/b2b-edition/specs/api-v3/authentication.yaml
docs/b2b-edition/specs/api-v3/channel/channel.yaml
docs/b2b-edition/specs/api-v3/company/company.yaml
docs/b2b-edition/specs/api-v3/invoice_management/invoice/invoice.yaml
docs/b2b-edition/specs/api-v3/invoice_management/payment/payment.yaml
docs/b2b-edition/specs/api-v3/invoice_management/receipt/receipt.yaml
docs/b2b-edition/specs/api-v3/order/order.yaml
docs/b2b-edition/specs/api-v3/payment/payment.yaml
docs/b2b-edition/specs/api-v3/quote/quote.yaml
docs/b2b-edition/specs/api-v3/sales_staff/sales_staff.yaml
docs/b2b-edition/specs/api-v3/shopping_list/shopping_list.yaml
docs/b2b-edition/specs/api-v3/super_admin/super_admin.yaml
docs/b2b-edition/specs/api-v3/task/task.yaml
docs/b2b-edition/specs/api-v3/user/user.yaml

Added security information and clean up
* 
ping {names}
[B2B-1354]: https://bigcommercecloud.atlassian.net/browse/B2B-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-1354: [update] add security details and cleanup

---

docs/b2b-edition/specs/api-v3/quote/quote.yaml

Added the description for the quote status field to be consistent with the B2B Edition App.
The specific modifications are as follows.
* Modified **status** field in quote list query params
* Changed the field type to integer.
* Added the meanings of each status value in the description.
* Added allowed values
* Modified **status** field in quote response
* Changed the field type to integer.
* Added the meanings of each status value in the description.
* Corrected the incorrect status value in the response example.
N/A
[B2B-1418]: https://bigcommercecloud.atlassian.net/browse/B2B-1418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-1418: [update] modified quote status description

---

docs/b2b-edition/specs/api-v3/user/user.yaml

Update user.yaml to resolve parsing errors

---

reference/shipping.v2.yml

- Update V2 shipping document introducing channels
As a part of MSF project and introducing channels, we want to update our docs to reflect the new feature.
`channels` filed is the list of channels associated with a method.
N/A
ping @bigcommerce/team-shipping @bc-andreadao 
[SHIPPING-3046]: https://bigcommercecloud.atlassian.net/browse/SHIPPING-3046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(shipping): SHIPPING-3046 Update V2 shipping docs with channels

---

docs/b2b-edition/specs/storefront/storefront/catalog.yaml
docs/b2b-edition/specs/storefront/storefront/company.yaml
docs/b2b-edition/specs/storefront/storefront/order.yaml
docs/b2b-edition/specs/storefront/storefront/rfq.yaml
docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml
docs/b2b-edition/specs/storefront/storefront/shopping.yaml
docs/b2b-edition/specs/storefront/storefront/store.yaml

Updated BearerToken security scheme for B2B storefront specs to follow OAS spec. This is needed so they render under the Authorization section in the right way.

Update b2b bearer token to follow OAS spec

---

docs/store-operations/orders/index.mdx
reference/orders.v2.oas2.yml

added a note 
Enhancement:
Added a note: orders created through the v2 Orders API will not result in an order notification email being sent to the customer.
* 
ping {names}
[DEVDOCS-5701]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5701: [update] add notes about emails

---

reference/shipping.v2.yml

Relates to [PR 554](https://github.com/bigcommerce/docs/pull/554)
- Fix incorrect field in Shipping V2 API documentation.
(will use release note draft from [PR 556](https://github.com/bigcommerce/docs/pull/556), since that will go in the next changelog) 
@bigcommerce/team-shipping 
[DEVDOCS-6142]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6142: Shipping V2 API, update channel_ids field

---

docs/store-operations/orders/refunds.mdx
reference/orders.v3.yml

[ORDERS-5733](https://bigcommercecloud.atlassian.net/browse/ORDERS-5733)
* Added `fee` item type to refund API documentation
* 
[ORDERS-5733]: https://bigcommercecloud.atlassian.net/browse/ORDERS-5733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ORDERS-5733: [add] Order Fees to Refund documentation

---

docs/store-operations/shipping/msf-international-enhancements.mdx
reference/shipping.v2.yml

This PR fixes the `channel_ids` fields that were missed in [PR 632](https://github.com/bigcommerce/docs/pull/632)
- Fix incorrect field in Shipping V2 API documentation.
(will use release note draft from https://github.com/bigcommerce/docs/pull/556, since that will go in the next changelog)
Related PRs:
- [PR 632](https://github.com/bigcommerce/docs/pull/632)
- [PR 554](https://github.com/bigcommerce/docs/pull/554)
- [PR 556](https://github.com/bigcommerce/docs/pull/556)
[DEVDOCS-6142]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6142: Shipping V2 API, update channel_ids field (part 2)

---

reference/catalog/categories_catalog.v3.yml

Added the page query parameter.
Added meta> pagination fields to the response for products sort order query
Bug Fix
* 
ping {names}
[DEVDOCS-6148]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6148: [update] add pagination to GET product sort order

---

docs/integrations/hosted-analytics.mdx

* Update BODL documentation's `line_items` field
* We're happy to announce the new `line_items.coupon_amount` field in Big Open Data Layer for hosted storefronts, which indicates the coupon amount for a line item in a cart.
* Fixed a bug in the Big Open Data Layer documentation regarding which BigCommerce API field to which the `line_items.discount` maps.
@bigcommerce/team-data
[DEVDOCS-6141]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6141: BODL, update line_items fields

---

docs/storefront/stencil/themes/context/object-reference/schemas/product.yml

* product.id in productdetails resources should be an int
We have inconsistency between MSF and non-MSF stores where product.id is int and string. PR to fix it got merged, so the docs should be updated as well
https://github.com/bigcommerce/storefront/pull/3430
ping @bigcommerce/dev-docs 
[STRF-12752]: https://bigcommercecloud.atlassian.net/browse/STRF-12752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: STRF-12752 Product.id should integer instead of a string

---

reference/geography.v2.yml

1. Set default value for accept and content-type. Make swagger file consistent
2. When using autogenerated TS library we have an issue with types inconsistency. `country_id` is integer. Int is convertable to string, so there should be no issues
None
None

LOCAL-2603 Fix geo swagger definition

---

docs/storefront/widgets/index.mdx

Change the limit of customer widget templates per store from 1000 to 250.
Changed the limit of customer widget templates per store to 250.
* 
ping {names}
[DEVDOCS-6150]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6150: [update] change limit of customer widget templates per store

---

reference/pages.v3.yml

* add optional query param delete_children for v3 DELETE Pages API
* remove warning that's no longer relevant
Update https://developer.bigcommerce.com/docs/rest-content/pages#delete-pages to allow optional query param delete_children to replicate the same clean up behavior in Control Panel. 
https://github.com/bigcommerce/bigcommerce/pull/60682/files
ping @bigcommerce/dev-docs @bigcommerce/team-storefront
[STRF-12659]: https://bigcommercecloud.atlassian.net/browse/STRF-12659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

STRF-12659: Add optional query param delete_children for v3 DELETE Pages API

---

reference/catalog/products_catalog.v3.yml

* Add `channels_id:in` query parameter to Get All Products endpoint 
* Add `channels` to `include` query parameter for Get All Products and Get a Product endpoint
* Add `channels` array to response for Get All Products and Get a Product endpoint
The POST and PUT endpoints are not affected.
We're happy to announce that you can now retrieve the channels are assigned to a product when you get a product through the Catalog API. You can also filter products by the channel when you Get All Products.
Get all Products endpoint:
cc @bigcommerce/multi-catalog-storefront-team , @kristinapototska

Add channels to Get all Products and Get a Product

---

reference/shipping.v2.yml

Also fixes a typo
* Added mention of the platform limit for `zip` type shipping zone location
* Fix a typo for `Get a shipping zones` to `Get a shipping zone`
* There is now a platform limit of 40000 zip type shipping locations per store. Users can no longer add more than 40000 zip type locations on their store.
* Fixed a typo on the `Get a shipping zone` section.
Work done in PR: https://github.com/bigcommerce/bigcommerce/pull/60942
ping @bigcommerce/team-shipping 
[SHIPPING-2884]: https://bigcommercecloud.atlassian.net/browse/SHIPPING-2884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SHIPPING-2884 add mention of platform limit for 'zip' type shipping zone locations

---

docs/storefront/stencil/cli/install.mdx

* Rosetta mode is not really required for Stencil CLI. TLDR: I received a new laptop with Mac M2 and was able to reproduce some edges cases and found the easiest way how to resolve them
Examples:
* Updated Stencil CLI installations docs for Mac 
[](https://github.com/bigcommerce/stencil-cli/issues/995#issuecomment-2520835069)
[STRF-12861]: https://bigcommercecloud.atlassian.net/browse/STRF-12861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: STRF-12861 Update stencil cli installation docs

---

docs/storefront/headless/customers.mdx
docs/storefront/headless/end-to-end-guides/graphql-storefront.mdx
docs/storefront/headless/index.mdx
reference/customers.v2.yml

added the workflow using the customer access token
* 
ping {names}
[DEVDOCS-5897]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5897: [update] add new headless workflow

---

docs/b2b-edition/specs/api-v3/authentication.yaml

Edit recently added parameter CustomerAccessToken in the b2b io/auth/customers/storefront endpoint.
Enhancement: Fixed the type for the CustomerAccessToken to correctly represent the object type.
<!-- Provide an entry for the release notes using simple, conversational language. Don't be too technical. Explain how the change will benefit the merchant and link to the feature.
NA
ping {names}

fix cat related info to auth/customers/storefront endpoint

---

reference/catalog/product-modifiers_catalog.v3.yml

remove allOf and make option_values an array, not an object
* 
ping {names}
[DEVDOCS-5908]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix object error, option_values should be an array

---

reference/orders.v2.oas2.yml

Orders v2 api
* Get Fee
* Create Fee
* Update Fee
* The newly-released custom order level fees on the orders is now available to use. Now, you’ll be able to apply and manage the order level fee via orders v2 api, and fetch any applied fees on an order.

feat(orders): ORDERS-6751 Doc update with order level fee in order apis

---

docs/storefront/graphql/orders.mdx

Add order metafield examples to orders page
* We're happy to announce order metafields are now available in the Storefront GraphQL API.
* 
ping {names}
[DEVDOCS-6144]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6144: [update] Add examples to orders page

---

reference/customers.v3.yml

Made changes per Akshat's review
Enhancement
* 
ping {names}
[DEVDOCS-6055]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6055: [update] update per Akshat

---

reference/carts.v3.yml
reference/checkouts.sf.yml
reference/checkouts.v3.yml

Promotion Manager now allows merchant to explicitly set display name of the promotion (for both coupon and automatic promotion). 
* v3 checkout management api expose display_name for each coupon object in `coupons` and `cart.coupons`
* v3 cart management api expose display_name for each coupon object in `coupons`
* for storefront cart/checkout api, adjust the wording for coupon displayName to reflect the promotion change.
`coupons`:
`coupons`:
`cart.coupons`:
`cart.coupons`:
`coupons`:
ping @bigcommerce/team-checkout @bigcommerce/dev-docs 
[CHECKOUT-8827]: https://bigcommercecloud.atlassian.net/browse/CHECKOUT-8827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(checkout): CHECKOUT-8827 update doc to reflect new exposed "display name" field of the coupon

---

reference/tax.v3.yml

* Add `target` object to Tax Provider Connection API docs. Includes `country_codes` and `subdivision_codes` fields.
- Allows users to inspect where their tax provider connection is active. Useful for determining if there are outstanding steps in the merchant's tax provider configuration.
[TAX-2166]: https://bigcommercecloud.atlassian.net/browse/TAX-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add target field object (with country_codes, subdivision_codes) to Tax Provider Connection API docs

---

reference/shipping.v2.yml

* Fixed some issues with the Channel IDs documentation for Shipping Methods.
Spotted while reviewing some relatively recent changes to this documentation. 
Link: https://developer.bigcommerce.com/docs/rest-management/shipping-v2/shipping-method#create-a-shipping-method
[SHIPPING-3046]: https://bigcommercecloud.atlassian.net/browse/SHIPPING-3046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix channel IDs field documentation for shipping methods

---

docs/integrations/tax.mdx
reference/tax_provider.yml

* Added a note about document submission operations directly within our API reference.
We keep getting tax providers miss this key detail, so we're hoping this change helps reduce the number of these questions.
"Note" style is lifted from the nearby Tax Provider Connection API documentation.
Related docs: https://developer.bigcommerce.com/docs/rest-contracts/tax

Add note about document submission operations

---

docs/integrations/webhooks/events/index.mdx
docs/webhooks/callbacks/_all.yml
docs/webhooks/callbacks/store_modifier_updated.yml
docs/webhooks/callbacks/store_option_updated.yml

* Removed global store context from options and modifiers webhooks
* Fixed the webhook documentation for options and modifiers. You can only trigger the `store/option/updated` and `store/modifier/updated` webhooks by updating the option or modifier in the context of a channel and locale. 
cc @bigcommerce/team-catalog-ops  @kristinapototska

Remove global store context from options and modifiers webhooks

---

docs/b2b-edition/headless.mdx

Add new B2B storefront headless doc
* 
ping {names}
[DEVDOCS-5858]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5858:[new] add headless channel doc

---

reference/promotions.v3.yml

**Note: don't merge this PR until the experiment [PROJECT-6889.promotion_display_name_field](https://app.launchdarkly.com/projects/default/flags/PROJECT-6889.promotion_display_name_field?env=production&env=development&env=test&env=integration&env=staging&selected-env=production) completely ramped up**
New field "display_name" in the Promotions v3 API
- POST/PUT request body:
- POST/PUT/GET response: 
- New field "display_name" in PUT/POST request body of the Promotions v3 API
- New field "display_name" in PUT/POST/GET response  of the Promotions v3 API
as above
N/A
[PROMO-1123]: https://bigcommercecloud.atlassian.net/browse/PROMO-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(promotions): PROMO-1123 new field "display_name" in the Promotions v3 API

---

reference/shipping.v3.yml

* Updating the v3/shipping/settings endpoint from POST to PUT as this endpoint updates settings.
* Added new property - `out_of_zone_delivery_message` where this is used to update the out of zone delivery message that resides in `manage/settings/shipping`
[POST to PUT change](https://github.com/bigcommerce/bigcommerce/pull/60914)
[Out of zone delivery message field addition to shipping/settings endpoint ](https://github.com/bigcommerce/bigcommerce/pull/60916)
[Exposing the PUT method in v3/shipping/settings](https://github.com/bigcommerce/api-proxy-java/pull/3293)
Screenshot:
ping @bigcommerce/team-shipping @bc-andreadao 
[SHIPPING-3163]: https://bigcommercecloud.atlassian.net/browse/SHIPPING-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

chore(shipping): SHIPPING-3329 Update documentation of the v3/shipping/settings endpoint

---

reference/tax_provider.yml

* Added a note to our Tax Provider API commit operation reference to describe the relationship to the document submission strategy store tax setting.
Change is on the back of some confusion from a tax partner recently.

Add note about our new document submission strategy setting

---

docs/integrations/tax.mdx

* Added a section to our Tax Provider API guide to describe avoiding infinite loops - which is a topic that has caused some disruption a handful of times over the years.
[TAX-2194]: https://bigcommercecloud.atlassian.net/browse/TAX-2194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tax Provider API guide: add note about infinite loops

---

reference/orders.v3.yml

* Order transactions end point will return 503 in case if it is not able to get transactions data from bigpay
Sample 503 response
Related to https://github.com/bigcommerce/bigcommerce/pull/61192
ping @bigcommerce/team-payments @bigcommerce/team-orders 
[PAYMENTS-10239]: https://bigcommercecloud.atlassian.net/browse/PAYMENTS-10239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Order transactions return 503

---

docs/store-operations/pricing/calculations.mdx

Moved customer group discounts and bulk pricing after Product modifier in the table.
Bug fix: Moved customer group discounts because they are shown before modifier rules when they apply after, as does bulk pricing.  
* 
ping {names}
[DEVDOCS-6175]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6175: [update] update order of operations

---

reference/orders.v2.oas2.yml

…
* Updated description for shipping_cost_inc_tax & shipping_cost_ex_tax in prep for stricter validation
* 
[DEVDOCS-6190]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Management API][Orders] DEVDOCS-6190 Update orders shipping_cost_X_tax descriptions

---

reference/form_fields.sf.yml

* Feature is now in GA
* Removing Beta messaging from doc
* Storefront Form Fields API endpoint is now GA.
* We've removed the Beta messaging from the documentation.
ping {names}
[DEVDOCS-6186]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6186 - Remove Beta label from Form Fields Doc

---

reference/tax_settings.v3.yml

* Removed deprecated `show_inclusive_in_control_panel` field from Tax Settings API.
* Added `control_panel_price_display_strategy` field to Tax Settings API.
* Updated available Tax Settings API fields, new option available for controlling tax price display in the control panel.
[TAX-2184]: https://bigcommercecloud.atlassian.net/browse/TAX-2184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove deprecated field, add new control panel price display strategy field

---

reference/shipping.v2.yml

On-page links for Shipping Methods to range object properties and settings object properties returned incorrect anchors. Updated links to match correct anchors.
Also updated Range Object Properties table in the Get a Shipping Method section to match style of other Range Object Properties table.
* Links for settings object properties and range object properties point to correct anchors in-page
* Range object properties tables have consistent content styling and text.
* Fixed broken links in the Shipping Methods endpoint documentation.
* Updated text of Range Object Properties tables to match similar content in other areas of the doc.
ping {names}
[DEVDOCS-4171]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …

DEVDOCS-4171 - fix broken in-page links

---

docs/start/authentication/customer-login.mdx

* Updated Customer SSO to allow passing a `enable_persistent_cart` field which determines whether or not to merge carts during customer SSO login (when Persistent Cart is enabled)
* Added Customer SSO support for Persistent Carts
n/a
ping @bigcommerce/team-storefront 
[STRF-12557]: https://bigcommercecloud.atlassian.net/browse/STRF-12557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

STRF-12557: Update Customer Login SSO documentation for new "enable_persistent_cart" field

---

docs/storefront/wordpress/platform-integration/code.mdx

Update reference link
Bug Fix
* 
ping {names}
[DEVDOCS-6180]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6180: [update] update plugin code reference link

---

reference/settings.v3.yml

* The Create Favicon Image endpoint has a file size limit that was not previously documented
* Files larger than 10 MB will return a 422
* Updated doc to include reference to file size limit
* Added 422 to the responses list
ping {names}
[DEVDOCS-6185]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6185 - Update endpoint to include file size limit

---

docs/integrations/apps/unified-billing/example-queries.mdx

Provide a bulleted list in the present tense
* Adding in the new scope filters that we are adding as a part of the other PR's in this ticket to allow for end users to filter by scope (store's in this case)
Add related PRs, salient notes, ticket numbers, etc.
https://github.com/bigcommerce/merchant-subscription-manager/pull/345
https://github.com/bigcommerce/api-proxy-java/pull/3340
ping {names}
[BRP-17278]: https://bigcommercecloud.atlassian.net/browse/BRP-17278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BRP-17278 Add scope filter for SubscriptionsQuery

---

docs/b2b-edition/specs/api-v3/address/address.yaml
docs/b2b-edition/specs/api-v3/company/company.yaml
docs/b2b-edition/specs/api-v3/order/order.yaml
docs/b2b-edition/specs/api-v3/super_admin/super_admin.yaml
docs/b2b-edition/specs/storefront/storefront/shopping.yaml

See slack conversation: https://bigcommerce.slack.com/archives/C57SQ401K/p1737758629012029
Removed the apostrophe from the summary in order to fix links
* 
* 
ping {names}

remove-apostrophe-from-summary

---

reference/customers.v3.yml

* update v3 get customers api docs based on cursor pagination
* update v3 get ffvs api docs based on cursor pagination
* correct the value of meta for v3 post/put customers
* Feature: Cursor pagination is now available to Customers V3 - Get All Customers
* Feature: Cursor pagination is now available to Customers V3 - Get Customer Form Field Values
* Fixed: Corrected the value of meta for the response of Customers V3 - Create/Update Customers
[CUST-3623]: https://bigcommercecloud.atlassian.net/browse/CUST-3623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(customers): CUST-3623 update customers api docs based on cursor pagination

---

reference/catalog/category-trees_catalog.v3.yml

Made `tree_id` and `parent_id` anyOf
Bug Fix: Removed required for `tree_id` and `parent_id`.
* 
ping {names}
[DEVDOCS-6198]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6198: [update] updated Create Categories schema

---

reference/subscribers.v3.yml

#NO TICKET
Added the consents array to the PUT and POST request body schema and examples.
See slack conversation: https://bigcommerce.slack.com/archives/C57SQ401K/p1737710187469379
Enhancement
* 
ping {names}

Added consents array to put and post request bodies

---

reference/segments.v3.yml

Added 10 concurrent limits to the following endpoints:
Create Segments
Update Segments
Create Shopper Profiles
Added concurrent limits to Create Segments, Update Segments, and Create Shopper Profiles endpoints.
* 
ping {names}
[DEVDOCS-6197]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6197: [update] add concurrent limits

---

reference/catalog/products_catalog.v3.yml

Adding and updating product images by URL both have a maximum URL length of 255
* Adding and updating product images via URL has a maximum length limit of 255 characters
* This limit is reflected specifically for POST and PUT endpoints on Product Images
* Updated POST and PUT endpoints for Product Images to include URL character length limit of 255
ping {names}
[DEVDOCS-6205]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6205 - Add character limit for PUT and POST product image

---

reference/shipping_provider.yml

add missing ttl object to response body
See slack conversation: https://bigcommerce.slack.com/archives/C57SQ401K/p1738596845318689
* 
Bug Fix: Added missing optional field
* 
ping {names}

Ad `ttl` to shipping rates response body: [update] add missing ttl object to response body

---

docs/storefront/headless/index.mdx

JWT Session-Sync is limited to three unsuccessful attempts before IP is locked temporarily.
* JWT style login has a security limit of three failed attempts before temporarily locking the IP address making calls.
* Added call-out note about limit to the Headless Login section.
ping {names}
[DEVDOCS-6183]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6183 - add callout about authorization limit

---

docs/b2b-edition/specs/api-v3/authentication.yaml

* The [B2B Storefront Auth Token API](https://developer.bigcommerce.com/b2b-edition/apis/rest-management/auth#get-a-b2b-storefront-token) response does not return a token as a string, it returns it as an array of strings. 
* No functional change, just updating the documentation to be more accurate. 
Screenshot of response from API:
ping {names}

fix: token property in b2b storefront auth token response should be array

---

archive/storefront/nextjs-commerce/nextjs-commerce-v1.mdx
docs/integrations/apps/index.mdx
docs/store-operations/customers/index.mdx
docs/store-operations/segments/definitions.mdx
docs/storefront/wordpress/deployment/index.mdx
docs/storefront/wordpress/themes/index.mdx
reference/settings.v3.yml

- Fixed the Building for Catalyst link
* 
ping {names}
[DEVDOCS-6222]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6222: [update] fix links

---

docs/storefront/stencil/start/index.mdx

Added callout alerting devs of minimum version to remain PCI compliant with respect to nonce-based authorization.
* PCI 4.0 Section 6.4.3 requires nonce-based authorization, which has not been present previously.
* As of Cornerstone 6.16.0, nonce-based authorization and SRI features are implemented natively.
* A notice of the requirement and action are included in Stencil documentation.
* Added a call-out regarding PCI 4.0 Section 6.4.3 and upgrading to the current version of Cornerstone.
ping {names}
[DEVDOCS-6171]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6171 - Add call-out for PCI 4.0

---

docs/storefront/cart-checkout/open-checkouts/pci-compliance-guide.mdx

Providing a developer guide for updating custom checkout to include PCI DSS 4.0 Section 6.4.3 compliance features
* PCI DSS 4.0 Section 6.4.3 requires the inclusion of nonce-based authentication and SRI for checkout pages
* BigCommerce provides this functionality via updated features in control panel settings and Open Checkouts
* This provides a guide for developers for the use of the functionality.
* Created new guide for setting up PCI compliant features on checkout
SME review waived by GTM team.
Navigation update to be requested and managed separately.
ping {names}
[DEVDOCS-6170]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6170 - [New Doc] Guide for PCI on Checkout

---

docs/start/authentication/customer-login.mdx

* Update the Customer JWT payload reference to clarify that the `enable_persistent_cart` flag is ignored if you are using the JWT for the `loginWithJwt` GraphQL mutation.
* Persistent cart is now supported on all GraphQL login mutations
n/a
[STRF-12301]: https://bigcommercecloud.atlassian.net/browse/STRF-12301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

STRF-12301: Update Customer JWT payload reference

---

reference/shipping.v3.yml

* Providing documentation for `v3/shipping/settings/{channel_id}` endpoint.
* Updating property name for `out_of_zone_delivery_message` in `v3/shipping/settings` endpoint to `out_of_delivery_zone_message`
* Added missing http error responses
[Out of delivery zone message property update](https://github.com/bigcommerce/bigcommerce/pull/61705)
[Channel based settings endpoint](https://github.com/bigcommerce/bigcommerce/pull/61225)
[Published route in api-proxy](https://github.com/bigcommerce/api-proxy-java/pull/3348)
[SHIPPING-3449 Update name of out of delivery zone message property](https://bigcommercecloud.atlassian.net/browse/SHIPPING-3449)
[SHIPPING-3336 Create an v1/internalapi endpoint for channel based out of delivery message](https://bigcommercecloud.atlassian.net/browse/SHIPPING-33 …

chore(shipping): SHIPPING-3338 Publish documentation for v3 channel based out of zone delivery message

---

reference/catalog/products_catalog.v3.yml

* Add new sort field to get products
* Endpoint `v3/catalog/products` now support sorting by `calculated_price`
ping @bigcommerce/team-catalog 
[CATALOG-11019]: https://bigcommercecloud.atlassian.net/browse/CATALOG-11019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CATALOG-11019: Add new sort field to get products

---

docs/storefront/cart-checkout/guide/graphql-storefront.mdx

changed the documentation to explain the completeCheckout mutation will return a payment JWT token (for the storefront flow).
* `completeCheckout` mutation no longer returns access token with server payment context, instead it will return a payment JWT token with `checkout` payment context that can be used in the storefront flow. 
ping @bigcommerce/team-checkout 
[CHECKOUT-8921]: https://bigcommercecloud.atlassian.net/browse/CHECKOUT-8921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(checkout): CHECKOUT-8921 Change graphql storefront document to reflect the change of JWT payment token with checkout payment context

---

docs/store-operations/settings/locales.mdx

[LOCAL-2692](https://bigcommercecloud.atlassian.net/browse/LOCAL-2692)
Fix GraphQL Admin API link in Locales Configuration section
Fix GraphQL Admin API link in Locales Configuration section
[LOCAL-2692]: https://bigcommercecloud.atlassian.net/browse/LOCAL-2692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LOCAL-2692: fix GraphQL Admin API link in Locales Configuration section

---

docs/b2b-edition/authentication/hosted-auth.mdx
docs/b2b-edition/specs/api-v3/authentication.yaml

* The navigation items for Authentication pages now read "Authentication" instead of "Auth"
* Links to Authentication pages are updated to reflect the change
* Authentication endpoints now live on the root page for their family (e.g. Storefront Authentication)
* Navigation items and links related to B2B Edition authentication have been updated to be more readable and user friendly.
ping {names}
[DEVDOCS-6221]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update references to Auth docs

---

reference/catalog/products_catalog.v3.yml

* Add custom_url field to POST v3 product 409 error
* Endpoint `POST v3/catalog/products` now failed product creation when `custom_url` is not unique with 409 error code.
ping @bigcommerce/team-catalog 
[CATALOG-10610]: https://bigcommercecloud.atlassian.net/browse/CATALOG-10610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CATALOG-10610: Add custom_url field to POST v3 product 409 error

---

docs/b2b-edition/specs/storefront/storefront/rfq.yaml

Callout added for storefront quote creation pricing validation.
* Price validation occurs for all "storefront quote creation" API calls.
* Failing validation, an error is raised and logged.
* We've added pricing validation to storefront quote creation.
* The validation check prevents invalid prices from being passed from the storefront.
* Custom prices are still allowed in the server-to-server endpoint.
ping {names}
[DEVDOCS-6266]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6266 - Price Validation for Storefront Quote Creation

---

docs/b2b-edition/specs/api-v3/company/company.yaml

Moving forward, account hierarchies feature is enabled by default for new stores. Updated note about availability to reflect this.
* Account Hierarchies feature is enabled by default on all new B2B Edition stores.
* The feature may be requested, provided prerequisites are met.
* All new B2B Edition stores will have Account Hierarchies available.
ping {names}
[DEVDOCS-6315]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6315 - Account Hierarchies enabled by default

---

docs/storefront/stencil/themes/templates/checkout-confirmation.mdx

Blueprint references were IDd in this doc, and they have been removed.
* References to Blueprint are no longer useful, and the apps referenced are now deprecated, so references are being removed.
* We've removed references to Blueprint under Bluecheck and Rebilia apps.
* The apps were deprecated, so we've removed the full sections.
ping {names}
[DEVDOCS-6301]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6301 - Remove Blueprint features

---

reference/catalog/products_catalog.v3.yml

Removed product ID from complex rule schema.
Confirmed adjusters have correct schema.
* Complex rules PUT/POST bodies no longer have product_id as its presence confuses usage.
* We've removed the reference to product_id from the Complex Rules PUT/POST bodies to prevent confusion over usage.
* Including product_id in the body overrides the parameter, which can result in applying or updating rules where they should not be.
* The parameter is required, so the body occurrence is removed.
ping { @megdesko  }
[DEVDOCS-6309]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6309 - update complex rule schema

---

reference/orders.v2.oas2.yml

* adds `total_tax` to the order response body (it was missing previously)
* adds `orderFee_Resource` to represent the link url we return for fees when not doing eager loading
* updates `fees` to be either the url link or the loaded nested fee payload
* adds `''` as valid payment_status value https://github.com/bigcommerce/bigcommerce/blob/master/app/model/Orders/PaymentStatus.php#L30
#Release notes draft
Orders Update
- v2 Orders- Corrected schema details for various fields in the V2 Orders API.
[ORDERS-6924]: https://bigcommercecloud.atlassian.net/browse/ORDERS-6924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update order v2

---

docs/storefront/graphql/data-events.mdx

Create a new article for the Data Events API.
* 
ping {names}
[DEVDOCS-6321]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6321: [new] Data events API

---

docs/integrations/webhooks/events/channels.mdx
docs/integrations/webhooks/events/inventory-location.mdx

Simplified webhooks pages and made them consistent
We decided to not implement the name changes as requested in DEVDOCS-4975.
* 
ping {names}
[DEVDOCS-6053]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6053: [update] make webhook tables consistent

---

docs/integrations/webhooks/overview.mdx

* Add [Hookdeck Console](https://console.hookdeck.com?provider=bigcommerce) to the webhook **Tools** table
The text in the table is potentially a bit long. I felt the additional context and references were useful. However, I wasn't sure how to test running the rendered version of the docs locally. Happy to iterate on edits.

Add Hookdeck Console to webhook tools table

---

reference/orders.v3.yml

Update `orders.v3.yml` to include a previously undocumented field `tax_adjustment_amount` for refunds and refund quotes
* Add new option including `tax_adjustment_amount` for POST request body for `/orders/{order_id}/payment_actions/refunds_quotes`, mutually exclusive with the existing `items` payload.
* Add new option including `tax_adjustment_amount` for POST request body for `/orders/{order_id}/payment_actions/refunds`, mutually exclusive with the existing `items` payload.
* Extend description of `items` in the GET/POST response body for `/orders/{order_id}/payment_actions/refunds` to indicate that the `items` array will be empty if `tax_adjustment_amount` was used to create the refund.
* 
[ORDERS-6930]: …

doc(orders): ORDERS-6930 update Refund API docs to include `tax_adjustment_amount`

---

docs/b2b-edition/specs/api-v3/invoice_management/invoice/invoice.yaml

The customField object is available in the the request body of the Update an Invoice endpoint. A description of the object and its component fields, as well as examples, have been added to the endpoint's information.
* Added customField object and component fields to the list of fields in the request body of Update an Invoice
* Added customField object and component fields to the example request
* Added usage information and examples for the customField object in Update an Invoice
[DEVDOCS-6358]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6358 - Add custom field object information to Update an Invoice

---

reference/catalog/category-trees_catalog.v3.yml

Handle url parameter absence in GET a category tree request documentation
* Added missed url parameter in GET a category tree request documentation
ping {names}
[CATALOG-11250]: https://bigcommercecloud.atlassian.net/browse/CATALOG-11250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(catalog): CATALOG-11250 Handle url parameter absence in GET a category tree request documentation

---

docs/b2b-edition/models/response/code-array-message.yaml
docs/b2b-edition/models/response/code-array-meta.yaml
docs/b2b-edition/models/response/code-message.yaml
docs/b2b-edition/models/response/code-meta.yaml
docs/b2b-edition/models/response/code-object-message.yaml
docs/b2b-edition/models/response/code-object-meta.yaml

* Responses in B2B generally follow one of 7 formats, which currently have to be re-typed in every document. By creating models of six of these formats, we can save a measure of effort across all B2B specs. Example usage of the models follows:
```yaml
'200':
description: OK
content:
application/json:
schema:
allOf:
- $ref: "https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/response/code-object-meta.yaml"
- properties:
code:
default: 200
meta:
properties:
message:
default: "SUCCESS"
data:
properties:
userId:
type: integer
description: "The unique ID for the user."
```
While it may not seem like this is more efficient, the equivalent structure would require four extra lines typed repeatedly across all docs. It's a small saving, but it's still cleaner than …

DEVDOCS-6366 - create reusable response models

---

reference/customers.v3.yml

* Delete incorrect `responses/MetafieldCollectionResponse` component
* Add correct `200` response for GET /v3/customers/{customerId}/metafields
* Add correct `200` response for GET /v3/customers/{customerId}/metafields/{metafieldId}
* Fixed API documentation for GET /v3/customers/{customerId}/metafields and GET /v3/customers/{customerId}/metafields/{metafieldId} responses
Fixes https://github.com/bigcommerce/docs/issues/912

Fix customers/{customerId}/metafields GET responses

---

reference/tax_properties.v3.yml

* Adding a new `type` field to dictate whether property is associated to `PRODUCT` or `CUSTOMER`
* Currently, field is optional and has a default value of `PRODUCT`
* The new `/tax/customers` endpoint (for configuring customers with said properties) will be documented on a seperate page, in a seperate PR.
ping @bigcommerce/team-tax 
[TAX-1750]: https://bigcommercecloud.atlassian.net/browse/TAX-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(tax): TAX-1750 add type field to tax properties API docs

---

reference/tax_provider.yml

* Add new `tax_properties` field to the `customer` object, within Tax Provider API requests.
* Customer tax properties now available in Tax Provider API requests. Note: requires tax properties to be configured via the Tax Properties API, as well as setting property values via the Tax Customer API.
[TAX-1749]: https://bigcommercecloud.atlassian.net/browse/TAX-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(tax): TAX-1749 Include new tax_properties field for customer object within Tax Provider API requests

---

reference/tax_provider.yml

* Adjust customer tax properties example.
Driving change is the online parsing engine did not appreciate the empty array in this context. So, instead, we're using an actual example - which is more descriptive and hence helpful anyway.
N/A
[TAX-1749]: https://bigcommercecloud.atlassian.net/browse/TAX-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust customer tax properties example

---

docs/b2b-edition/specs/api-v3/quote/quote.yaml

Reformatted file.
Added new copy.
Added missing fields.
* Quotes includes new, thorough descriptive copy.
* Quotes includes previously missing fields.
* Quotes is reformatted to make effective use of components.
* As part of our ongoing content refresh for B2B Edition developer documentation, we've fully refreshed the Server-to-Server Quotes documentation. This includes
* New, thorough descriptive copy
* Inclusion of previously missing fields from several endpoints
ping { @CNanninga @bc-Vince }
[DEVDOCS-6246]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6246 - Quotes refresh

---

docs/b2b-edition/headless.mdx

* Article title reflects that steps are for non-Catalyst frameworks
* Link to API Accounts article in Step 1 uses standard URL instead of directing to specific text 
* Includes an introduction with a callout to Catalyst's B2B-specific documentation
* Step 6 now has an accompanying screenshot of the Headless Storefronts area of the B2B Edition control panel
* The article now reflects that it is geared toward non-Catalyst frameworks, and provides a link to Catalyst-specific instructions for integration.
[DEVDOCS-6212]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6212:[Update]B2B Refresh - Non-Catalyst Channel Setup

---

reference/tax_customers.v3.yml

* Adding documentation for the new `/v3/tax/customers` endpoint, for configuring customer tax data (currently just `tax_properties`)
* Added new `/v3/tax/customers` endpoint for managing customer tax data.
* Supports the following operations:
* `GET`: Retrieve tax data for one or more customers.
* `PUT`: Add or update tax properties for customers.
* `DELETE`: Remove tax data for specified customers.
- Still todo - add new endpoint to our [store operation docs](https://developer-beta.bigcommerce.com/docs/store-operations/tax/tax-properties).
ping @bigcommerce/team-tax 
[TAX-1750]: https://bigcommercecloud.atlassian.net/browse/TAX-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(tax): TAX-1750 add docs for `/v3/tax/customers` endpoint

---

docs/store-operations/tax/tax-customers.mdx
docs/store-operations/tax/tax-properties.mdx

* Adding documentation for the new `/v3/tax/customers` endpoint, for configuring customer tax data (currently just `tax_properties`)
* Adding new tax properties `type` field to dictate whether property is associated to `PRODUCT` or `CUSTOMER`
* Added a new optional `type` field to tax properties, allowing you to specify whether a property is associated with a product or a customer. If not set, it will default to `PRODUCT`.
* Added new `/v3/tax/customers` endpoint for managing customer tax data. Supports the following operations:
* `GET`: Retrieve tax data for one or more customers.
* `PUT`: Add or update tax properties for customers.
* `DELETE`: Remove tax data for specified customers.
* API reference PR - https://github.com/bigcommerce/docs/pull/927
ping @bigcommerce/team-tax …

docs(tax): TAX-1750 add store operations docs for tax customers and tax property type field

---

reference/tax_properties.v3.yml

* Mark Tax Properties API field as required.
* Remove default.
Aligns with future, intended state. This field is currently available and will soon be required.
* Tax Properties API now requires the type field (may be CUSTOMER or PRODUCT type).
[TAX-1744]: https://bigcommercecloud.atlassian.net/browse/TAX-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mark Tax Properties API field as required, remove default

---

reference/price_lists.v3.yml

Products and SKU webhooks are not fired when Price List record is changed. Corrected Usage Notes and deleted links to hooks.
* Products and SKU webhooks are not fired when Price List record is changed. 
* Usage notes incorrectly states that Price Lists directly relates to products.
* Products and SKU webhooks are linked under Additional Information.
* Updated Usage Notes to clarify that Price Lists are not directly related to Products. 
* Removed links to Products and SKU webhooks from Additional Information to help avoid confusion.
[DEVDOCS-6369]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6369 - Update - Clarify Price List related webhooks

---

reference/tax_provider.yml

With some nearby work, I noted a lack of links to our Tax Properties API documentation. Would be helpful to further guide users as to what the concept is speaking to.
* Add links to Tax Properties API for related fields within Tax Provider API documentation.
* Tax Properties API links added to Tax Provider API documentation.

Add tax properties API links to related fields

---

reference/tax_provider.yml

Hearing from a case where the merchant sounds like they are misunderstanding some related behaviour, prompting a small clarification to this field description.
* Adding explicit note about how the request `transaction_date` is intended to feed into the tax provider's response.
* Clarify Tax Provider API `transaction_date` field usage.

Add explicit detail about tax quote transaction date interaction

---

reference/tax.v3.yml
reference/tax_classes.v2.yml
reference/tax_provider.yml

We were previously advised that `x-internal` is no longer used. So, to stop any further copy pasting, removing it.
* Removed all `x-internal` items from tax documentation.
N/A

Remove x-internal from tax documentation

---

reference/pages.v3.yml

* Link row in the Page Types table should contain a reference to RFC 3986 standards.
* Added link to RFC standards under "link" in Page Types table. 
ping @bc-terra

DEVDOCS-6352 - Update - Page links should follow RFC 3986 standards

---

docs/start/best-practices/index.mdx

Added a section about cursor pagination
* 
* 
[DEVDOCS-6327]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6327 - Add cursor pagination

---

reference/checkouts.v3.yml

Responses including checkout data should have the field `tax_included`. Added to the Checkout schema.
* Documentation now includes reference to the `tax_included` field.
* 
[DEVDOCS-6373]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6373 - Add flag to responses

---

reference/pricing.sf.yml

* Pricing now supports requests with `customer_id` and not just `customer_group_id`
* Added the `customer_id` field to the request body.
* Updated the list of required fields.
ping { @megdesko @bc-Vince @bigcommerce/dev-docs-team }
[DEVDOCS-6376]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6376 - add customer_id field

---

docs/storefront/graphql/multi-language-support.mdx

Added header-based example to request as new tab
* The documentation states that locales may be pulled either by a query directive or by a header. The examples now include both methods.
* 
ping { @CNanninga @bigcommerce/dev-docs-team }
[DEVDOCS-6336]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6336 - Include header-based example

---

reference/widgets.v3.yml

Adding widget template limit for all channels (5000) to: https://developer.bigcommerce.com/docs/rest-content/widgets/widget-template
Changed
"Note: There is a limit of 1000 custom widget templates per store."
to
"Note: There is a limit of 1000 custom widget templates per channel, and a limit of 5000 across all channels."
* Updated widget template limits in Content API reference.
@bc-terra - Ready for review.
[DEVDOCS-6350]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6350 | Correct limits of total custom widget templates

---

docs/b2b-edition/specs/api-v3/quote/quote.yaml

Fixed relative URL paths on "Quote" page links so that they direct to the corresponding endpoint sections in "Quotes".
* Fixed links on the "Quote" overview page so that they direct to the corresponding endpoint sections
* We've updated links to endpoints on the Quote overview page to enhance usability.
[DEVDOCS-6398]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6398 - Fix URL paths in "Quote" (S2S)

---

docs/start/about/index.mdx

Added table of GraphQL headers as documentation doesn't currently exist
* We now have GraphQL headers for features of a request
* `x-bc-gql-query-hash` - a hash for identifying specific requests
* `x-bc-gql-operation-type` - the operation type used in the request
* `x-bc-gql-operation-name` - the name of the operation, if given
* We've added documentation for our GraphQL response headers, including several for quickly identifying specific requests.
ping { @bigcommerce/team-api-platform @bigcommerce/dev-docs-team }
[DEVDOCS-6375]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6375 - New GraphQL response headers

---

docs/storefront/graphql/storefront-scripts.mdx

- New doc specific to GraphQL `scripts` query
- Provides basic guidance and examples
* There's a new GraphQL query for fetching and using storefront scripts in BigCommerce
* We've added new storefront scripts query to GraphQL that fetches scripts for easy deployment in non-Stencil storefronts.
N/A
ping { @bigcommerce/dev-docs-team  }
[DEVDOCS-6405]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6405 - Fetch Scripts via GraphQL

---

docs/b2b-edition/specs/api-v3/order/order.yaml

Reformatted file.
Added new copy.
Added missing fields.
Called out independent Companies behavior considerations and legacy extra fields
* Introduction includes helpful general information, including some of the uncommon fields shared among endpoint responses.
* Endpoints now include summaries with usage information
* Request and response bodies are up-to-date, showing all available fields and parameters
* YAML file is organized into several schema to reduce redundant text lines and improve efficiency for subsequent edits
* As part of our ongoing content refresh for B2B Edition developer documentation, we've fully refreshed the Server-to-Server Quotes documentation. This includes
* New, thorough descriptive copy
* Inclusion of previously missing fields from several endpoints
* Expansion …

DEVDOCS-6254 - Content Refresh - "Order" (S2S)

---

reference/promotions.v3.yml

Fix display issue for DraftCouponPromotions
Replace all anyOf with more accurate oneOf
Fix display issue for docs.
Here it should say "Draft Coupon Promotion" not "BasePromotion"
Also while im here fixed a few "anyOf" that should say "oneOf"
* 
ping @bigcommerce/team-orders @bc-terra 
[DEVDOCS-6407]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(docs): DEVDOCS-6407 fix display issue

---

docs/integrations/tax.mdx

* Add "building resilience" section to Tax Provider API docs.
In response to our second significant report on this topic.
* Added additional guidance around API best practices to our Tax Provider API implementation guide.
[TAX-2428]: https://bigcommercecloud.atlassian.net/browse/TAX-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add "building resilience" section to Tax Provider API docs

---

docs/b2b-edition/specs/storefront/storefront/rfq.yaml

Added revisions from the post-publish feedback in [PR 902](https://github.com/bigcommerce/docs/pull/902).
* The `quote_default_pdf` config now includes a description of what it does.
* The list of quote email templates includes all available templates and no longer displays an unavailable template.
* The `inventory` field in the `productList` array includes the correct enum values.
* We've updated the following field descriptions to include more information on accepted values and how to use them:
* `inventory`
* `emailTemplate`
* `quote_default_pdf`
ping @bc-terra @bc-eduardogamboa 
[DEVDOCS-6237]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6237 - Refresh Quotes (SF)

---

docs/integrations/apps/guide/requirements.mdx

Added an explanation of how to properly mark an order's source with an app.
* The Functionality requirements now clarify how to specify the mandatory external source for apps that create orders.
* Provided information on the `external_source` field required for apps that  create orders.
[DEVDOCS-6423]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6423 - Add new rule for Payments Partners

---

docs/b2b-edition/specs/api-v3/quote/quote.yaml

Updated `decimalPlaces` description to call out that you can display up to 4 decimal places.
* The description for the `decimalPlaces` field clarifies that you can display up to 4 decimal places.
*  The description for the `decimalPlaces` field now clarifies that you can display up to 4 decimal places on quotes.
[DEVDOCS-6414]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6414 - Call out decimal place limitations in Quotes (S2S)

---

docs/storefront/stencil/themes/context/handlebars-reference.mdx

* Most file types are served the same as documented.
* Some image types are now served from a new path.
* We've updated how our CDN handlebar helper (via WebDAV) serves images of types
* `.jpg` or `.jpeg`
* `.gif`
* `.png`
* Other filetypes are still served as expected
ping { @bigcommerce/dev-docs }
[DEVDOCS-6408]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6408 - clarify cdn path for images

---

docs/storefront/stencil/themes/context/object-reference/schemas/page-type.yml
docs/storefront/stencil/themes/context/object-reference/schemas/page.yml
docs/storefront/stencil/themes/context/object-reference/schemas/urls.yml
reference/pages.v3.yml
reference/store_content.v2.yml

* Remove rss feed page type from public documentation
* Remove rss feed page type from a list of supported page type since it has been deprecated many years ago.
ping {names}
[STRF-13437]: https://bigcommercecloud.atlassian.net/browse/STRF-13437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

STRF-13437: Remove rss feed page type from public documentation

---

reference/tax_properties.v3.yml

* Add information about our newly introduced `type` filter on our Tax Properties API.
* Tax Properties API now supports filtering results by type (customer or product).
Related PR: https://github.com/bigcommerce/bigcommerce/pull/64034
[TAX-2314]: https://bigcommercecloud.atlassian.net/browse/TAX-2314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add type filter to tax properties API documentation

---

docs/b2b-edition/specs/api-v3/invoice-management.yaml

Reverts bigcommerce/docs#1017
Following confirmation that the tag description does not add introductory content to a reference doc, I am reverting the content back to its original state.

Revert "Determine if tag descriptions show up as introductions in reference a…"

---

reference/promotions.v3.yml

* add 405 error code when method not allowed
* Update status 405 for bulk coupon codes generation
[ORDERS-7119]: https://bigcommercecloud.atlassian.net/browse/ORDERS-7119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ORDERS-7119 add 405 error code when method not allowed

---

docs/b2b-edition/specs/storefront/storefront/order.yaml

Reformatted file with reusable schemas.
Added new copy.
Added missing fields and parameters.
Called out legacy extra fields.
* Introduction presents helpful usage information, including the Company user permissions needed for the user associated with the storefront authToken.
* Endpoints now include summaries with usage information.
* Request and response bodies are up-to-date, showing all available fields and parameters.
* YAML file is organized into several schema to reduce redundant text lines and improve efficiency for subsequent edits.
* As part of our ongoing content refresh for B2B Edition developer documentation, we've fully refreshed the Server-to-Server Quotes documentation. This includes
* New, thorough descriptive copy
* Explanation of legacy information fields
* INclusion of …

DEVDOCS-6253 - Content Refresh - "Orders" (Storefront)

---

reference/orders.v2.oas2.yml

* Mark `order_taxes.tax_rate_id` as deprecated.
* Document `order_taxes.sales_tax_id` (this has actually actually been in the response for a while now).
- To support a wider range of use cases, the `order_taxes.tax_rate_id` (int) is now deprecated and will be removed in the near future. Please update to use the `order_taxes.sales_tax_id` (string) field.
[TAX-2463]: https://bigcommercecloud.atlassian.net/browse/TAX-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mark order_taxes.tax_rate_id as deprecated, document sales_tax_id

---

docs/integrations/apps/unified-billing/example-queries.mdx

* Previously, merchants were unable to cancel subscriptions between the end of a free trial and the next billing cycle date.
* Now, merchants that cancel in this window will be prorated the fees and charged on their next invoice.
* We've adjusted the way cancellation is managed for unified billing so that cancellations post-trial and pre-billing cycle will be prorated instead of preventing cancellation.
[DEVDOCS-6442]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6442 - proration update for UB

---

reference/storefront_tokens.v3.yml

* The `allowed_cors_origin` field was not displaying correctly, and now it is.
* We've fixed the display of fields associated with `POST` bodies.
ping { @bigcommerce/dev-docs }
[DEVDOCS-6464]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6464 - fix issue around displaying fields

---

docs/graphql-account/users.mdx

* Removed password linked mutation as part of security upgrade.
* To enhance security, we've removed the ability to create a control panel user account with password via GraphQL. Users can still be added to an account using the non-password linked mutation.
[DEVDOCS-6410]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6410 - Remove password connected mutations

---

docs/store-operations/translations/brands.mdx
docs/store-operations/translations/categories.mdx
docs/store-operations/translations/index.mdx
docs/store-operations/translations/locations.mdx

* Documentation for filtering translations by resourceId for brands, categories, and locations resource types.
Updated documentation for filtering translations by resourceId
ping @bc-janet 
[DEVDOCS-6453]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6453 - add resourceId to translation gql docs

---

reference/promotions.v3.yml

* Feedback provided from merchant that the response code for creating a coupon code is 201 and not 200.
* Documentation has been updated to reflect
Documentation updated to reflect proper 201 response code when creating a single coupon code.
[DEVDOCS-6484]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6484 - update create coupon code response from 200 to 201

---

docs/storefront/catalyst/development/b2b.mdx

* B2B support call to action link redirects to the BC support cases guide 
* Changing call to action in the support section of the Catalyst B2B docs
[B2B-3407]: https://bigcommercecloud.atlassian.net/browse/B2B-3407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-3407 - update B2B support cta

---

reference/pages.v3.yml

* Added 4000 page limit to pages v3 api spec
The Pages v3 API Spec now includes page limits for reference.
ping @bc-terra
[DEVDOCS-6456]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6456 - add page limit to pages v3 API spec

---

docs/storefront/stencil/themes/foundations/directory-structure.mdx

* Added a callout to two separate pages for maximum directory depth in Stencil
* [No update to the platform, only documentation]
* Added a callout to two separate pages for maximum directory depth in Stencil
[DEVDOCS-6499]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6499 - add alert about maximum directory depth in Stencil Themes

---

docs/b2b-edition/specs/api-v3/quote/quote.yaml

Updated the `userEmail` description to clarify valid values and default behavior.
* Updated `userEmail` description to clarify usage and fallback behaviour.
* Updated `userEmail` description to clarify usage and fallback behaviour.
[DEVDOCS-6486]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6486 - Enhance userEmail field description

---

docs/b2b-edition/specs/storefront/storefront/rfq.yaml

Fixed links to the Quote Statuses section of the spec file overview.
* The `status` field's description now correctly links to the information on Storefront API quote status values.
* We've fixed link quote status information in the article.
[DEVDOCS-6537]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6537 - Fix link to Quote Statuses content in Quotes Storefront API reference
