docs/api-docs/getting-started/about-our-api.mdx
reference/customers.v2.yml
reference/customers.v3.yml
reference/subscriptions.sf.yml

* Update the link to the Customers Overview
* Update broken links
ping {names}

(no ticket): [update] Various, fix Customers Overview link

---

docs/api-docs/orders/orders-api-overview.mdx

* remove links that don't fit
* 
* https://github.com/bigcommerce/dev-docs/issues/2016
ping {names}

Issue-2016 from dev-docs: Orders Overview, remove links that don't fit

---

docs/api-docs/storefront/widgets/widget-builder.mdx
docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx

Ensuring the node sass versions are consistent
* 
ping {names}
[DEVDOCS-5703]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5703: node sass version

---

.github/workflows/deploy.yml

* Specify that the site should build using a fresh copy of the docs, not a cached version
* 
ping {names}
[SELFDEV-415]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-415: [repo] deploy.yml, fix deploy cache undefined error

---

reference/price_lists.v3.yml

* Remove duplicate sentence in the parameters of the Price List Records GET
* No release notes for this ticket.
ping {names}
[DEVDOCS-5378]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5378]: [update] Price lists, Price lists records

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.mdx

* Update channel name to an allowed value
* 
ping {names}

(no ticket): [update] Embedded Checkout, update channel name

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.mdx

* #30 
* update callout about where to find channels
* Updated channels information in the Embedded Checkout tutorial
* #30
* #23
* #25 
ping {names}

ISSUE-30: [update] Embedded Checkout tutorial, update callout about where to find channels

---

reference/webhooks.v3.yml

* https://github.com/bigcommerce/api-specs/issue/1376
* Update datatypes for id and timestamps
* Updated datatypes in the Webhooks V3 specifications.
* https://github.com/bigcommerce/api-specs/issue/1376
ping {names}

ISSUE-1376: [update] Webhooks, update datatypes for ID and timestamps

---

reference/orders.v2.oas2.yml

Updated the `order_source` definition.
See Slack conversation: https://bigcommerce.slack.com/archives/C96P5T3J4/p1704292037915419
* 
ping {names}
[DEVDOCS-5706]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5706: [update] updated order_source definition

---

docs/stencil-docs/customizing-checkout/checkout-confirmation-injection.mdx

{{{stylesheet '/assets/css/theme.scss'}}}
should be
{{{stylesheet '/assets/css/theme.css'}}}
* 
ping {names}
[DEVDOCS-5729]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5729: [update] fix typo

---

docs/stencil-docs/customizing-checkout/custom-order-confirmation.mdx

Provide information and a reference to how to localize the files.
* 
ping {names}
[DEVDOCS-5111]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5111 : [update] add localization information

---

docs/stencil-docs/customizing-checkout/custom-order-confirmation.mdx

Removed space to fix the link
* 
ping {names}

remove extra space

---

reference/catalog/category-trees_catalog.v3.yml

* #59
* attempt to address issue-59
* 
ping {names}

ISSUE-59: [update] Catalog Category Trees Categories, significant improvements

---

docs/stencil-docs/storefront-customization/using-disqus.mdx

Updated the steps
* 
ping {names}
[DEVDOCS-5747]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5747: [update] update steps

---

reference/carts.v3.yml

changing the return type on the entity id property to return a string, instead of an integer.
* 
ping {names}
[DEVDOCS-5705]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5705: [Update] changed ID from integer to string

---

docs/api-docs/headless/overview.mdx

* Remove broken link that leads to a different URL
* 
ping {names}
[DEVDOCS-5709]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5709]:[update] Headless Overview, Remove broken resource link

---

docs/stencil-docs/storefront-customization/using-disqus.mdx

Updated to reflect menus for non-msf stores.
* 
ping {names}
[DEVDOCS-5747]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5747: [update]update for non-msf

---

docs/stencil-docs/storefront-customization/using-disqus.mdx

It is more accurate to say "For non-MSF storefronts, navigate to Storefront" since step 3 starts with Themes.
* 
ping {names}
[DEVDOCS-5747]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5747: [Update] clean up

---

docs/stencil-docs/installing-stencil-cli/node-sass.mdx

No Ticket
for scenario 1, we can change "Please review and publish anytime prior to January 31, 2024." to "Please review and publish at your convenience"
* 
ping {names}

no ticket-update per Jaime

---

reference/orders.v2.oas2.yml

* Add component for `external_order_id`
* Add the ref to the Get All Orders Parameters
* Now includes `external_order_id` in the Get All Orders parameters. Add the parameter to your request to include Order IDs from external systems.
[DEVDOCS-5748]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5748]:[update] Add `external_order_id` component

---

reference/store_information.v2.yml

* update things that didn't look good
* see previous PR, no specific follow on note here
* #78
ping {names}
[DEVDOCS-5756]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5756: [update] Store Information, fix suboptimal syntax

---

reference/channels.v3.yml
reference/store_information.v2.yml

* Update example to include recently-added properties
* Add descriptions for recently added properties
* none needed
* #78
* #80
ping {names}
[DEVDOCS-5756]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5756: [update] Store Information, update descriptions + example

---

reference/orders.v2.oas2.yml

* #83
* create dedicated schemas for order shipping providers
* See release notes for #84
* #83
* #84
ping {names}

ISSUE-83: [update] Orders V2, abstract shipping provider schemas

---

docs/stencil-docs/installing-stencil-cli/incompatible-directives.mdx
docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx

remove jan 31 deadline
* 
ping {names}
[DEVDOCS-5755]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5755: [Update] remove jan 31 date

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.mdx

Changed redirect URL
* 
ping {names}
[DEVDOCS-5760]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5760: [Update] change URL to reflect embedded checkout

---

docs/stencil-docs/developing-further/catalog-price-object.mdx

Updated the definition for sale price
* 
ping {names}
[DEVDOCS-5707]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5707: [Update} update sale price definition

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.mdx
docs/api-docs/customers/customer-login-api.mdx

* 
* We've updated the Embedded Checkout tutorial to indicate that the `channel_id` is required for a Customer Login JWT used in the embedded checkout process.
ping {names}
[DEVDOCS-5765]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5765: [update] Embedded Checkout tutorial, add channel_id to Customer Login JWT

---

docs/api-docs/getting-started/authentication.mdx
docs/api-docs/payments/payments-api-overview.mdx
docs/api-docs/storefront/graphql/graphql-api-overview.mdx

Specific OAuths are not needed
* 
ping {names}
[DEVDOCS-5045]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5045: [update] Remove non-token oauth scopes from token creation docs

---

docs/api-docs/headless/orders.mdx

Correcting the processing payments URL
* 
ping {names}
[DEVDOCS-5652]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5652: [update] correct URL

---

archive/rest-catalog/placeholder.mdx

* create archive directory
* not needed
* Supports #97
ping @olysenko @bc-traciporter
[DEVDOCS-5771]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CATALOG-9219]: https://bigcommercecloud.atlassian.net/browse/CATALOG-9219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5771: [repo] Add archive directory 

---

reference/catalog/products_catalog.v3.yml

Changed `primary_images` to `primary_image`
fixed typo
* 
ping {names}
[DEVDOCS-5761]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5761: [update]fix typo, change primary_images to primary_image

---

docs/api-docs/getting-started/deprecations-and-sunsets.mdx

* Add Customer V2, Delete All Customer Groups endpoint to the deprecations and sunsets document
* No comms please. :)
ping {names}
[DEVDOCS-5795]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5795] - [new] Update Deprecations and Sunsets to include Customer V2, Delete All Customer Groups

---

reference/customers.v2.yml

* Remove the DELETE endpoint in the Customer Groups path
Release notes are not needed. See slack conversation for details.
https://bigcommerce.slack.com/archives/C039JSWHH50/p1708108312150699?thread_ts=1708108271.060429&cid=C039JSWHH50
* 
ping {names}
[DEVDOCS-5768]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5768]: [deprecate] CustomersV2: Delete All Customer Groups endpoint

---

docs/api-docs/apps/guide/apps-06-callbacks.mdx

* Replaced description from user to store owner for the following properties:
* user.id
* user.email
* user.locale
* No update here, just a correction.
ping {names}
[DEVDOCS-5799]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5799] Update from user to store owner in Handling Callbacks properties table

---

reference/catalog/products_catalog.v3.yml

Updated PUT Custom Fields endpoint
not needed
* 
ping {names}
[DEVDOCS-5771]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5771-Nataliaa-catalog-updates: [update] custom field updates

---

reference/catalog/products_catalog.v3.yml

Add `create_redirect` to custom_url
* 
ping {names}
[DEVDOCS-5798]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5798: [update] add create_redirect to custom_url

---

reference/catalog/product-variants_catalog.v3.yml
reference/catalog/products_catalog.v3.yml

* Removed duplicated variants array in the Update a Product array
* Ensured variant ID is in the variants array in the Update Products (Batch) and Create a Product endpoints
Bug Fix - removed duplicate variants arrays and correct schemas
* 
ping {names}
[DEVDOCS-5366]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5366: [update] resolve misleading variants array

---

docs/msf/msf-overview.mdx
reference/channels.v3.yml

* update channels type and platform information
* We've added a new `catalyst` [channel platform](/docs/rest-management/channels) specifically for Catalyst storefronts. Using this type will more seamlessly connect your Catalyst storefront to the store control panel.
ping @bc-andreadao
[DEVDOCS-5790]:
https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-5790]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-5790]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5790: [new] Channels, add catalyst platform type

---

docs/api-docs/storefront/graphql/graphql-carts-and-checkout.mdx

Added note about entityId
* 
ping {names}
[DEVDOCS-5347]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5347: [update] add note about entityId

---

docs/api-docs/apps/guide/apps-02-types.mdx

* Change statements from 'beta testing before testing' to 'testing before submitting' since beta testing doesn't apply to draft apps
* Statement Correction: Apps > Types of Apps >#visibility clears up confusion around app testing. Beta testing  is not applicable for draft apps.
ping {names}
[DEVDOCS-5805]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS:5805] - [revise] Apps and Integrations, change statements around beta testing before submitting an app

---

docs/api-docs/payments/payments-api-overview.mdx

Add BlueSnap Direct Payment Gateway
The newly-released BlueSnap Direct payment gateway is available for raw card and stored instrument data. See the list of [compatible payment gateways].
* 
OLD PR: https://github.com/bigcommerce/dev-docs/pull/1918
OLD DEVDOCS ticket: [DEVDOCS-4905](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4905)
ping {names}
[DEVDOCS-5266]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-4905]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5266: [update] add BlueSnap Direct to payment gateways

---

reference/marketing.v2.yml

Added recommendation for using the query parameters
* 
ping {names}
[DEVDOCS-5559]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5559:[update] added notes about filters

---

reference/catalog/products_catalog.v3.yml

Updated url_zoom definition
maybe under bug fixes
* 
ping {names}
[DEVDOCS-5243]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5243:[update] update url_zoom definition

---

docs/api-docs/catalog/products-overview.mdx

*  Fixed description about  option type that is set by default from radio buttons to rectangles in Create a variant using the product endpoint operation
*  Fixed description about  option type that is set by default from radio buttons to rectangles in Create a variant using the product endpoint operation
@bc-traciporter

CATALOG-8923: [update] Catalog, fix description in Create a variant using the product endpoint chapter

---

reference/checkouts.v3.yml

Updated the discount_amount
* 
ping {names}
[DEVDOCS-5128]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5128: [update] update discount_amount definition

---

docs/api-docs/apps/guide/apps-13-publishing.mdx

* Swap from "dark background" to "color background" for Alternate Logo details
* Minor correction
ping {names}
[DEVDOCS-5815]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5815]: [revise] Publishing an App, Fill in Details, minor correction

---

docs/stencil-docs/reference-docs/front-matter-reference.mdx
docs/stencil-docs/storefront-customization/using-front-matter.mdx

Update docs on usability of YAML front matter with custom templates
* 
Removed the contradictory information regarding YAML front matter in the templates/pages subdirectory.
* 
ping {names}
[DEVDOCS-5464]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5464: [update] Update front-matter support information

---

reference/catalog/brands_catalog.v3.yml

* Remove parameters
* Update request body 
[DEVDOCS-5770]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5770 [update]: Catalog API, update brand metafields

---

reference/catalog/products_catalog.v3.yml

Update the following endpoints to include terms of service and privacy policy:
- [Create a Product](https://developer.bigcommerce.com/docs/rest-catalog/products#create-a-product) 
- [Update Products Batch](https://developer.bigcommerce.com/docs/rest-catalog/products#update-products-batch)
- [Update a Product](https://developer.bigcommerce.com/docs/rest-catalog/products#update-a-product)
- [Create a Product Video](https://developer.bigcommerce.com/docs/rest-catalog/products/videos#create-a-product-video)
- [Update a Product Video](https://developer.bigcommerce.com/docs/rest-catalog/products/videos#update-a-product-video)
[DEVDOCS-5794]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5794 [update]: Catalog API, add terms of service and policy

---

reference/carts.v3.yml

Added file upload options example 
Added example for using the file upload option to create a cart.
ping {names}
[DEVDOCS-5792]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5792: [update] add file upload option example

---

reference/themes.v3.yml

Added in missing fields:`is_active` and `updated_at`
Bug Fix
Added in missing fields to Get all themes and get a theme endpoints
ping {names}
[DEVDOCS-5830]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5830: [update] added missing fields

---

reference/catalog/category-trees_catalog.v3.yml

Updated the example response for Get all Categories 
* 
ping {names}
[DEVDOCS-5732]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5732: [update] Added tree_id to example response body

---

docs/api-docs/webhooks/webhook-events.mdx

* Add information to store/orders/created table informing that this fires on all orders including those with incomplete payments, failed payments, and unprocessed orders.
* no release notes needed here.
ping {names}
[DEVDOCS-5772]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5772]: [revise] Webhooks, Webhook event Orders

---

reference/subscribers.v3.yml

Updated description  for consents 
n/a
ping {names}
[DEVDOCS-5841]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update per Bala

---

docs/stencil-docs/installing-stencil-cli/node-sass.mdx

Updated the timeline section since node sass has been sunsetted
N/A
ping {names}
[DEVDOCS-5846]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5846 [Update] update timeline section

---

docs/api-docs/apps/guide/apps-13-publishing.mdx

* Switch the first steps in the guide since the process has since updated
* Update images of the UI as it is no longer up-to-date
* Revisited out-of-date screenshots that now provide the correct steps needed to ceritfy an application
ping {names}
[DEVDOCS-5816]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5816]: [update] Apps Publishing, update screenshots and first step details

---

models/_root/price.yml

See slack conversation: https://bigcommerce.slack.com/archives/C57SQ401K/p1709333656392169
n/a
ping {names}
[DEVDOCS-2781]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding price.yml to root directory

---

models/theme_objects/_all.yml

Add a reference to price.yml to display file.
n/a
ping {names}
[DEVDOCS-2781]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a reference to price.yml

---

docs/api-docs/headless/end-to-end-guides/graphql-storefront.mdx
docs/api-docs/headless/end-to-end-guides/rest-management.mdx

* Review and revise end-to-end GraphQL Storefront API headless checkout flow article
* 
ping {names}
[DEVDOCS-5665]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5665: [update] GQL SF API end to end headless checkout flow

---

docs/api-docs/storefront/widgets/widget-versioning-tutorial.mdx

- Fix incorrect method for updating widget 
[DEVDOCS-5817]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5817 [update]: Theme & Content APIs, update widget guide

---

models/category/shop_by_price.yml

Updated the shop_by_price description
* 
ping {names}
[DEVDOCS-5717]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5717: [update] Update shop_by_price.yml

---

docs/api-docs/users/overview.mdx

Jira: [ANA-4629](https://bigcommercecloud.atlassian.net/browse/ANA-4629)
* Updating the AddUserToStore documentation to reflect the security patch that the IAM team tackled as part of ANA-4629. The vulnerability there was that it was possible for attackers to enumerate through user ID's and retrieve all the emails of users throughout the platform if they were successful in using an ID that belongs to someone. The IAM team recommends that we instead use email as the identifier for users as part of this specific mutation, however we are still allowing for a set of accounts that have existing Users API tokens to continue using the original API contract as before.
* 
ping @mikelopez100 
[ANA-4629]:
https://bigcommercecloud.atlassian.net/browse/ANA-4629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

[DEVDOCS-5864]/[ANA-4629] Users, Update AddUserToStore docs to reflect security patch 

---

docs/api-docs/provider-apis/tax/overview.mdx

* Numerous simplifications to our tax provider development flow.
* Most importantly, this update includes changes to how we enable tax providers (the enable button is going away, replaced by the provider connection target panel in provider settings).
* See inline comments for more detail.
[TAX-1968]: https://bigcommercecloud.atlassian.net/browse/TAX-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5657 [update]: Tax Provider API, update development flow 

---

docs/api-docs/webhooks/webhook-events.mdx

#No Ticket - [Issue 207](https://github.com/bigcommerce/docs/issues/207)
Store Address is listed twice so I removed one of them.
* 
ping {names}

remove duplicates of Store Address

---

reference/catalog/product-variants_catalog.v3.yml

Clarified the values for cost_price. See Slack conversation for details.
https://bigcommerce.slack.com/archives/C05GVCPFW66/p1712082685986189
* 
ping {names}

Issue-196: [update] cost_price

---

docs/api-docs/webhooks/webhook-events.mdx

Added clarification for the Price List records docs
* 
ping {names}
[DEVDOCS-5855]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5855: [Update] clarify price list webhooks docs

---

docs/api-docs/webhooks/setting-up-webhooks.mdx

Removed npm ngrok installation steps
* 
ping {names}
[DEVDOCS-5848]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5848: [Update] remove ngrok installation steps using npm

---

docs/api-docs/storefront/graphql/graphql-carts-and-checkout.mdx

Add create cart metafield example
* 
ping {names}
[DEVDOCS-5819]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5819: [update] add cart metafields example

---

models/webhooks/store_order_transaction_created.yml

Update schema
The newly-updated `store/order/transaction/created` webhook now allows you to receive additional data for `transaction_status`, `transaction_type`, and `result` attributes.
* 
ping {names}
[DEVDOCS-5894]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5894: [update] update store/order/transaction/created

---

docs/api-docs/payments/payments-api-overview.mdx

* Added a link to the Stored Instruments doc
* Added a new section on Theme considerations
Clarified the workarounds needed when using Payment API on a headless storefront.
ping {names}
[DEVDOCS-5840]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5840: [update] add link to stored instruments, add theme considerations

---

docs/api-docs/webhooks/setting-up-webhooks.mdx

Still need to remove a command that causes a security threat.  The tutorial still works without it.
N/A
* 
ping {names}
[DEVDOCS-5848]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

updating due to security issue

---

reference/catalog/products_catalog.v3.yml

I closed PR 205 due to the merge conflicts and added my changes here.
Added channel_id as an optional field to existing catalog products v3 endpoints.
Confirm with @bc-romanliukshyn and @bc-alexandr-naumenko 
* 
ping {names}
[DEVDOCS-3840]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3840: [Update] replaces PR 205

---

docs/stencil-docs/customizing-checkout/checkout-sdk-quickstart.mdx

Added note about checkout.content_head since it is not mention in our docs
* 
ping {names}
[DEVDOCS-5857]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5857: [update] add note about checkout.content_head

---

reference/catalog/products_catalog.v3.yml

Reverts bigcommerce/docs#228
According to @bc-romanliukshyn these changes are not ready yet for channel support. So I am reverting the changes.

Revert "DEVDOCS-3840: [Update] replaces PR 205"

---

docs/api-docs/getting-started/deprecations-and-sunsets.mdx

added Stencil CLI to the Deprecations & Sunset article
Ask Jaime
* 
ping {names}
[DEVDOCS-5881]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5881: [update] add stencil cli

---

reference/catalog/categories_catalog.v3.yml

Updated the descriptions for page and limit descriptions
* 
ping {names}
[DEVDOCS-5900]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5900: [update] Edit descriptions for page and limit parameters

---

reference/orders.v3.yml

* Add missing value, `order_level_refunds_amount`, to the `orders/{order_id}/payment_actions/refund_quotes` request response example
* 
ping {names}
[DEVDOCS-5758]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5758]: [revise] OrdersV3, Add `order_level_refund_amount` to the orders/{order_id}/payment_actions/refund_quotes API

---

reference/orders.v3.yml

* Remove giftcertificate and storecredit values from gateway
* Add bigcommerce as a gateway value
* Remove status field from gift_certificate object
*  The latest updates are available for the Get Transactions APIs which now allows merchants to select BigCommerce as a Gateway type.
ping {names}
[DEVDOCS-3806]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3806: [update] Orders, Get transaction orders endpoint to include BigCommerce

---

docs/api-docs/customers/customer-login-api.mdx

* Replace invalid information in the callout in the Prerequisites segment; token should be created at the store-level and app must be installed to generate a token
* Corrected information in our Authentication docs. Customer login API had the wrong information for token creation. Users need store-level access to create a token. The app must be installed before creating a JWT.
ping {names}
[DEVDOCS-5667]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5667]: [revise] Authentication, Replace inaccurate information in Customer Login API callout

---

docs/api-docs/webhooks/about-webhooks.mdx

Update text for duplicate webhook
* 
ping {names}
[DEVDOCS-5206]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5206:[Update] update text for duplicate webhook

---

reference/checkouts.v3.yml

Added custom shipping to request body
* 
ping {names}
[DEVDOCS-5648]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5648: [update] add custom shipping

---

docs/legacy/v2-catalog-products/v2-products.mdx

- Fixed an incorrect statement that said SKUs were read-only
[DEVDOCS-5899]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5899 [update]: Legacy docs, update SKU

---

docs/stencil-docs/developing-further/customizing-printable-packing-slips.mdx

Add variables for packing slips
* 
ping {names}
[DEVDOCS-5156]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5156: [update] add variables for packing slips

---

reference/customers.v2.yml
reference/customers.v3.yml
reference/form_fields.sf.yml
reference/orders.v2.oas2.yml
reference/orders.v3.yml
reference/pages.v3.yml
reference/store_content.v2.yml
reference/storefront_tokens.v3.yml
reference/tax_rates_zones.v3.yml
reference/tax_zone_check.v3.yml
reference/webhooks.v3.yml
reference/widgets.v3.yml

* remove empty x-examples
* 
ping {names}

(no ticket): [update] API reference, remove empty x-examples

---

reference/orders.v3.yml

* add xml and multipart schemas where indicated
* 
ping {names}

(no ticket): Orders V3, add schemas for alt request body mime types

---

models/_root/category.yml

* Add empty properties to objects that didn't have them, per #202 
* 
ping @bc-traciporter

ISSUE-202: [update] Category object, add empty properties

---

reference/orders.v2.oas2.yml

DEVDOCS-5931 - Fix typo

---

docs/api-docs/partner/support.mdx

* #268 
* Update the support options available to developers
* We've updated our list of dev support options to include the Resource Hub.
ping @madisontillery @bc-traciporter

ISSUE-268: [update] Support options, update to reflect current resources

---

reference/carts.v3.yml
reference/catalog/brands_catalog.v3.yml
reference/catalog/categories_catalog.v3.yml
reference/catalog/product-variants_catalog.v3.yml
reference/catalog/products_catalog.v3.yml
reference/channels.v3.yml
reference/customers.v3.yml
reference/orders.v3.yml

Removed 500 status code from metafield docs
Carts
Channels
Customer
Catalog
Orders
n/a
* 
ping {names}
[DEVDOCS-5922]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5922: [Update] removed 500 status error code from metafield docs

---

reference/catalog/product-variants_catalog.v3.yml

Added missing `image_url` in the response body for the Create a Product Variant endpoint.
* 
ping {names}
[DEVDOCS-5917]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5917: [update] added missing image_url object

---

reference/catalog/products_catalog.v3.yml
reference/customers.v3.yml
reference/orders.v2.oas2.yml
reference/themes.v3.yml
reference/widgets.v3.yml

* remove duplicated parameters (as #274)
* mark request body for `updateProducts` operation as required
This PR actually fixes a little more than what is reported in #274. During development I noticed another problem (see commit 32bfcbb) which I decided to fix immediately instead of opening another issue. Feel free to discard this commit when merging the PR if that `required: false` is not an error.
ping @slsriehl @bc-tgomez

ISSUE-274: [fix] Remove duplicate parameters

---

reference/payments/process_payments.yml

* change x-examples to examples
* remove duplicate example
* remove ill-formatted examples
* remove curl example with no request body
* 
ping {names}

(no ticket): [update] Process payments, remove faulty examples

---

reference/catalog/product-variants_catalog.v3.yml

Added a note about how to obtain the option values needed in the create a product variant request.
* 
ping {names}
[DEVDOCS-5949]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5949: [update] added a note about option_values

---

reference/catalog/product-modifiers_catalog.v3.yml

This should be a DEVDOCS tickets, not a SELFDEV.  There specification file is fine. I just added a correct example.
* 
ping {names}
[SELFDEV-650]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-650 : [update] example for create a product modifier

---

reference/catalog/categories_catalog.v3.yml
reference/catalog/category-trees_catalog.v3.yml

Update description for category name.
* 
ping {names}
[DEVDOCS-5914]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5914: [Update] name definition

---

models/_root/comparisons.yml
models/_root/page.yml
models/_root/urls.yml

Updated theme objects (page, urls, and comparisons)
* 
ping {names}
[DEVDOCS-5518]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5518: [Update] update page, urls, and comparisons theme objects

---

models/_root/remote_api_scripts.yml

Added "No properties available for this object"
* 
ping {names}
[DEVDOCS-5518]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5518: [Update]remote_api_scripts.yml

---

models/_root/remote_api_scripts.yml

Fixed schema for remote_api_scripts
* 
ping {names}
[DEVDOCS-5518]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update remote_api_scripts.yml per Mark

---

reference/webhooks.v3.yml

Added information regarding the replacement for this endpoint.
* 
ping {names}

Issue-300: [update] Update webhooks.v3.yml

---

reference/abandoned_carts.v3.yml

* Move parameters in to place
* Fix format issues with schema
* No real changes, just small tweaks to the schema layouts.
ping {names}
[DEVDOCS-5854]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5854]: [revise] Abandoned carts V3, Clean up schema layout to use as example API

---

reference/pages.v3.yml

Updated the order and added titles for schemas
* 
ping {names}
[DEVDOCS-5642]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Devdocs-5642 [update] Pages V3

---

models/_root/settings.yml

Revert "DEVDOCS-5911 [new]: MSF / Stencil, add channels object to themes"

---

models/_root/price.yml
models/blog/posts.yml
models/cart/cartItems.yml
models/common/price.yml
models/common/product.yml
models/customer/orders.yml
models/product/price.yml
models/product/related_products.yml
models/theme_objects/_all.yml
models/webhooks/_all.yml

Add in refs for the price object
* 
ping {names}
[DEVDOCS-5818]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5818: update refs

---

docs/api-docs/apps/guide/apps-01-introduction.mdx
docs/api-docs/apps/guide/apps-02-types.mdx
docs/api-docs/apps/guide/apps-03-developing.mdx
docs/api-docs/apps/guide/apps-05-oauth.mdx
docs/api-docs/apps/guide/apps-06-callbacks.mdx
docs/api-docs/apps/guide/apps-07-users.mdx
docs/api-docs/apps/guide/apps-08-events.mdx
docs/api-docs/apps/guide/apps-10-buttons.mdx
docs/api-docs/apps/guide/apps-11-best-practices.mdx
docs/api-docs/apps/guide/apps-12-requirements.mdx
docs/api-docs/apps/guide/apps-13-publishing.mdx
docs/api-docs/partner/dev-portal-overview.mdx
docs/legacy/blueprint-themes/lng-variables.mdx
docs/legacy/blueprint-themes/product-filtering-toolkit.mdx

* Remove and/or update broken links
* 
ping {names}
[SELFDEV-687]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-687: [update] Remove and update broken links

---

reference/carts.v3.yml

Correct request body for cart redirect URL. Screenshot image of the payload is in the ticket.
Bug Fix
* 
ping {names}
[DEVDOCS-5963]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5963: [update] create redirect URL request body

---

models/common/amount.yml

Updated the type of the amount model to number and fixed description. This is likely the reason that the Price theme object isn't rendering.

Update amount.yml to fix data type

---

reference/catalog/categories_catalog.v3.yml

* Updated swagger file for Category Image, Sort Order endpoints
* Updated swagger file for Category Image, Sort Order endpoints
[CATALOG-9785]: https://bigcommercecloud.atlassian.net/browse/CATALOG-9785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CATALOG-9785: [update] Catalog, Category Images, Sort Order

---

reference/catalog/products_catalog.v3.yml

* Remove brand_name from response body
* Update swagger file for Products endpoints

CATALOG-9786: [update] remove brand_name from response body

---

docs/integrations/scripts.mdx

* Removed restrictions for scripts on All Pages.
Bug Fix
* 
ping {names}
[DEVDOCS-5383]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5383: [Update] remove All pages restrictions

---

reference/checkouts.v3.yml

Added note about enabling multiple coupons.
* We're happy to announce the ability to apply multiple coupons on a cart using the Checkout v3 API.
ping {names}
[DEVDOCS-5958]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5958: [Update] add note about multiple coupons

---

archive/rest-catalog/brands.v2.yaml
reference/catalog/brands_catalog.v3.yml

* Add swagger file for V2 Brands
* Update swagger file for V3 Brands
* Revert this PR
[CATALOG-9786]: https://bigcommercecloud.atlassian.net/browse/CATALOG-9786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CATALOG-9786: [update] Brands: REST Catalog

---

reference/carts.v3.yml
reference/catalog/brands_catalog.v3.yml
reference/catalog/categories_catalog.v3.yml
reference/catalog/product-variants_catalog.v3.yml
reference/catalog/products_catalog.v3.yml
reference/channels.v3.yml
reference/customers.v3.yml
reference/orders.v3.yml

add date created and date modified query parameters
* 
ping {names}
[DEVDOCS-5953]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5953: [update] add date created and date modified query parameters

---

docs/storefront/stencil/themes/context/object-reference/schemas/product.yml

custom_fields node appears to be out of order, which makes it hard to find. Moved it up to match alphabetical order, the same as all other nodes are sorted. 
* 
ping {names}

Update themes product.yml - move custom_fields node up to match alphabetical order

---

reference/locations.v3.yml

Added parameters to the GET batch metafields endpoint.
* 
ping {names}
[DEVDOCS-5953]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5953: [update] add date created and date modified

---

docs/storefront/graphql/examples/products.mdx

Added product video section
We're happy to announce the ability to query product videos using the storefront product graph.
* 
ping {names}
[DEVDOCS-5972]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5972: [update] product videos

---

reference/checkouts.v3.yml

Correct example and schema for Checkout Discounts
Chad Taylor approved the changes. See screenshot attached to the ticket.
Bug Fix
* 
ping {names}
[DEVDOCS-5990]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5990: [update] Update Add discount to checkout schema and example

---

docs/storefront/stencil/themes/context/object-reference/schemas/product.yml

Bug Fix: Added missing information
Screenshot of the missing information is in the ticket.
* 
ping {names}
[DEVDOCS-6004]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6004 [update] add fields for bulk_discount_rates & fix errors in file

---

docs/store-operations/payments/index.mdx
reference/payments/access-tokens_payments.v3.yml

* Added the expiration time for the PAT token.
* 
ping {names}
[DEVDOCS-6003]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6003 [Update] add token expiration time

---

reference/carts.v3.yml

Add the redirect URL expiration time
See slack conversation: https://bigcommerce.slack.com/archives/C0WC9CSJX/p1719949652260899
Added clarification for how long the cart redirect url is active.
* 
ping {names}

Add cart redirect url expiration time

---

docs/store-operations/catalog/graphql-admin/product-custom-fields.mdx

* Peer review for [PR 347](https://github.com/bigcommerce/docs/pull/347)
* 
ping {names}
[DEVDOCS-5957]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5957 [new]: MSF International Enhancements, edit custom_fields

---

docs/api-docs/getting-started/api-rate-limits.mdx

* Update API rate limits documentation
* Updated API rate limits documentation: Quotas now vary by plan and resources. Enterprise clients have new guidelines. Added methods for handling limits and optimizing requests.
ping {names}
[DEVDOCS-5629]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5629]: [Update] Getting Started, API Rate limits update

---

docs/start/best-practices/index.mdx

* Removed API rate limiting content from the doc as a new file exists around [API rate limits](https://developer.bigcommerce.com/docs/start/best-practices/api-rate-limits)
* Removed API rate limit content from the Best Practices section to streamline documentation and improve clarity for developers.
ping {names}
[DEVDOCS-5910]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-5910]: [remove] Best Practices, Remove API limit content from the Development doc

---

docs/api-docs/getting-started/api-rate-limits.mdx

No Ticket
* Fix title to match sentence casing rules
* 
ping {names}

[No ticket] Correction, Fix sentence case header

---

archive/storefront/blueprint/themes/global-variables.mdx

Added note to the shopPath variable
* 
ping {names}
[DEVDOCS-5988]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5988: [update] Update shopPath definition

---

docs/integrations/apps/guide/publishing.mdx
docs/integrations/apps/guide/requirements.mdx
docs/integrations/buy-online-pick-up-in-store/frequently-asked-questions.mdx

* Add MLI-compatibility requirements into BOPIS FAQs
* Update screenshot for dev portal
* Apps that are compatible with multi-location inventory use our Inventory API for inventory adjustments. Now, you can indicate whether an app is MLI-compatible when you submit an app in the Dev Portal.
[DEVDOCS-5142]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5142 [new]: Apps, update MLI-compatibility requirements

---

docs/store-operations/payments/index.mdx

Added TD Online Mart to the list of compatible payment gateways for both Stored Instruments and Raw Card Data
We're happy to announce that TD Online Mart is supported for both Stored Instruments and Raw Card Data.
Examples:
* The newly-released [X feature] is now available to use. Now, you’ll be able to [perform Y action].
* We're happy to announce [X feature], which can help you  [perform Y action].
* [X feature] helps you to create [Y response] using the [Z query parameter]. Now, you can deliver [ex, localized shopping experiences for your customers].
* Fixed a bug in the [X endpoint]. Now the [Y field] will appear when you click [Z option]. -->
* 
ping {names}
[DEVDOCS-5780]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

DEVDOCS-5780: [update] Added TD Online Mart

---

docs/storefront/graphql/customers.mdx

* Remove beta flag
* Remove beta callout
* Storefront  GraphQL Orders capabilities are now available to the public. You can now perform queries that fetch a customer's orders history, a specific customer order, and access order details. See a list of examples in [GraphQL Storefront API: Customers](https://developer.bigcommerce.com/docs/storefront/graphql/customers) and try them in the [BigCommerce GraphQL Playground](https://developer.bigcommerce.com/graphql-storefront/playground).
ping @jamie-mckenzie 
[DEVDOCS-6041]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-6041]: [update] Storefront GQL Orders object, Remove beta flags

---

reference/price_lists.v3.yml

* Fixed incorrect schema for Create Batch Price List Records
Examples:
* The newly-released [X feature] is now available to use. Now, you’ll be able to [perform Y action].
@bigcommerce/team-pricing 
[DEVDOCS-5921]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5921 [update]: Price List Records, fix incorrect schema 

---

docs/store-operations/pricing/price-lists.mdx

* Clarified the docs about what happens when a price record is deleted 
N / A
@bigcommerce/team-pricing 
[DEVDOCS-5938]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5938 [update]: Price Lists, deleting price record

---

docs/api-docs/getting-started/api-rate-limits.mdx

* update links to fix 404s
* N/A
ping @bc-tgomez

SELFDEV-761: [fix] API rate limits, fix 404s

---

docs/start/authentication/graphql-storefront.mdx

Addressed comments left by @chanceaclark 
https://bigcommerce.slack.com/archives/C056HLZC36W/p1722371294497539?thread_ts=1722370409.269799&cid=C056HLZC36W
* 
ping {names}
[DEVDOCS-5923]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update graphql-storefront.mdx per Chancellor

---

docs/store-operations/catalog/graphql-admin/product-custom-fields.mdx

* Update schema for setting product custom fields
@bigcommerce/team-multi-storefront, cc @kristinapototska 
[DEVDOCS-5957]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5957 [update]: MSF International Enhancements, update set product custom fields

---

docs/storefront/stencil/cli/install.mdx

Add installation steps for Rosetta
* 
ping {names}
[DEVDOCS-6043]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6043: [update] add Rosetta back for Macs

---

reference/catalog/product-variants_catalog.v3.yml
reference/catalog/products_catalog.v3.yml

This reverts commit 6252c6ad2016a2183f632c64f51079c34fb7270c.
Iryna said there was an incident and that the gtin can also be 14 digits. They are rechecking requirements and asked to rollback PR 401.
* 
ping {names}

Revert "DEVDOCS-6015: [Update] upc, mpn, gtin (#401)"

---

reference/price_lists.v3.yml

See slack conversation https://bigcommerce.slack.com/archives/C05DH8JCESU/p1722873887683529 
* update query parameters, request & response body schemas
N / A
@bigcommerce/team-pricing

DEVDOCS-6025 [update]: Price Lists, update query parameters, request & response body schemas

---

reference/orders.v3.yml

Just some phrasing change to make it more accurate.
No release note required
ping @bc-traciporter

update phrasing around concurrent refunds

---

reference/catalog/products_catalog.v3.yml

[No Ticket]
PR created to address https://github.com/bigcommerce/docs/issues/429 
Relevant slack [conversation ](https://bigcommerce.slack.com/archives/C05GVCPFW66/p1723140111438329)
Screenshot proof:
* Add create bulk pricing rules method to documentation
- Improve structure of yml file for bulk pricing rules
- Update documentation to include Create a Bulk Pricing Rule endpoint 
@bigcommerce/team-catalog

Issue 429 [No Ticket]: add POST bulk pricing rules

---

docs/b2b-edition/about/api-status-codes.mdx
docs/b2b-edition/about/index.mdx
docs/b2b-edition/authentication/headless-auth.mdx
docs/b2b-edition/authentication/hosted-auth.mdx

*  Apply style guide to the mdx files in our B2B Edition docs.
* No release note needed at this time.
ping {names}
[DEVDOCS-6071]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-6071]: [update] B2B-Edition, MDX style guide corrections

---

docs/webhooks/callbacks/store_priceList_deactivated.yml

* Add missing description pipe fix
* 
ping {names}
[DEVDOCS-6031]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS-6031-edit]: [revision] Webhooks, store_price_list_deactivated callback description clean up

---

docs/webhooks/callbacks/_all.yml
docs/webhooks/callbacks/store_priceList_activated.yml

* More description fixes in the `/webhooks/callbacks` folder
ping @bc-tgomez

Fix descriptions

---

docs/webhooks/callbacks/_all.yml
docs/webhooks/callbacks/store_priceList_activated.yml
docs/webhooks/callbacks/store_priceList_deactivated.yml

Changed `active: false` to active:false hoping to resolve errors
* 
ping {names}
[DEVDOCS-6031]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6031: removed backticks

---

reference/orders.v2.oas2.yml

Relevant slack conversation [here](https://bigcommerce.slack.com/archives/C04D0Q2LC/p1723233948507659)
* Update schemas/examples for Order Products & Order Shipments
N / A
@bigcommerce/team-orders 

DEVDOCS-6025 [update]: Orders V2, update Order Products & Order Shipments

---

reference/carts.sf.yml

Relevant slack conversation: https://bigcommerce.slack.com/archives/C0WC9CSJX/p1722957413324389
- Update schemas & query parameters
N / A
@bigcommerce/team-checkout 

DEVDOCS-6025 [update]: Storefront Carts, update schemas & query parameters

---

reference/orders.v3.yml

Relevant slack conversation https://bigcommerce.slack.com/archives/C96P5T3J4/p1723752403863899 
reposted https://bigcommerce.slack.com/archives/C9DGL6D8A/p1724174002476639 
* Update Orders V3 endpoints:
- Get Order Transactions
- Order (Batch) Metafields
- Order (Single) Metafields
N / A
@bigcommerce/team-orders 

DEVDOCS-6025 [update]: Orders V3, update order transactions

---

reference/carts.v3.yml

Fixed the meta object
Removed a required field from a  response object
Question
What is the required scope for Get Channel Cart Settings? The Carts scope is not working
* 
ping {names}

DEVDOCS-6025: [TEST-SPEC] Update carts.v3.yml

---

reference/carts.v3.yml

Removed duplicate authentication heading
* 
ping {names}

remove duplicate "Authentication" headings

---

docs/start/authentication/graphql-storefront.mdx
reference/storefront_tokens.v3.yml

Revert "DEVDOCS-6000 [new]: GQL Storefront API, add dev_mode field"

---

reference/catalog/brands_catalog.v3.yml

Removed requirement from response fields.
* 
ping {names}
[DEVDOCS-6023]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6023: [TEST SPEC] Update brands_catalog.v3.yml

---

docs/b2b-edition/specs/storefront/authentication.yaml

- Changed `storeFront` references to be `storefront`
- Changed `BC` references to be `BigCommerce`
ping @bigcommerce/dev-docs-team

Update B2B authentication.yaml

---

reference/customers.v2.yml

* Removed `date_created` and `date_modified` fields from the request body fields.
* Fixed the amount field.
Outstanding Question
-  Can someone confirm if the `none` enum is correct for `category_access` > `type`?
* 
ping {names}
[DEVDOCS-6023]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6023: [TEST SPEC] Update customers.v2.yml

---

reference/channels.v3.yml

* Updated the example in the Create a Channel Site from http to https
* Updated the example in the Create a Channel Site from http to https and added a note about using the Https protocol.
ping {names}

Issue-387: [update] remove url scheme

---

docs/store-operations/segments/promotions-api.mdx

#NO TICKET
Found broken links and fixing them
n/a
ping {names}

Update promotions-api.mdx - fix links

---

reference/catalog/products_catalog.v3.yml

Added channels as an optional field to existing /catalog/products v3 endpoints 
* We're happy to announce channels are available as an optional field in /catalog/products v3 endpoints which can help you  .......
ping {names}
[DEVDOCS-6090]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6090: [Update] Add channels

---

reference/storefront_tokens.v3.yml

Removed trailing slash from example
N/A - Bug Fix
ping {names}

Issue-377: [update] removed trailing slash 

---

reference/catalog/products_catalog.v3.yml

Revert "DEVDOCS-6090: [Update] Add channels"

---

docs/storefront/graphql/examples/index.mdx

Added example mutation to add a favicon.
I also want to update links to the storefront playground but not sure if they are correct.
* 
ping {names}
[DEVDOCS-6087]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6087: [update] add favicon to storefront GraphQL

---

docs/storefront/graphql/examples/index.mdx

fixing the language
* 
ping {names}

editorial change

---

reference/consent.sf.yml

Corrected the consent category numbers in file
Bug Fix
See feedback slack channel: https://bigcommerce.slack.com/archives/C04MTV8C2LE/p1726045801664739
ping {names}

fix consent categories numbers

---

docs/store-operations/catalog/graphql-admin/product-attributes.mdx
docs/store-operations/catalog/graphql-admin/product-basic-info.mdx
docs/store-operations/catalog/graphql-admin/product-custom-fields.mdx
docs/store-operations/catalog/graphql-admin/product-modifier-options.mdx
docs/store-operations/catalog/graphql-admin/product-seo-info.mdx
docs/store-operations/catalog/graphql-admin/product-url.mdx
docs/store-operations/catalog/graphql-admin/product-variant-options.mdx
docs/store-operations/catalog/msf-international-enhancements.mdx

[No Ticket]
See relevant comment [here](https://github.com/bigcommerce/docs/pull/347#discussion_r1667068684)
- Move table from a child page to the main overview page 
- Improve links from child pages to the main overview page 
N / A

[No Ticket]: MSF International Enhancements, improve links to overview page

---

reference/pages.v3.yml

Updated the description for `is_customers_only`.
Bug Fix
Updated the description for `is_customers_only`.
ping {names}
[DEVDOCS-6057]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6057: [update] is_customers_only

---

docs/storefront/cart-checkout/metafields.mdx

See https://bigcommerce.slack.com/archives/C57SQ401K/p1726511197971909?thread_ts=1726504262.910979&cid=C57SQ401K
Bug Fix - cart metafields will not work on REST Storefront Carts. Updated doc to alleviate confusion.
* 
ping {names}

cart-metafields-update

---

reference/promotion_settings.v3.yml

* Added documentation for future Promotion Settings REST API
* Added documentation for future Promotion Settings REST API
[PROMO-1051]: https://bigcommercecloud.atlassian.net/browse/PROMO-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROMO-1051: [add] Promotion Settings v3 REST contract

---

docs/integrations/apps/guide/publishing.mdx

added security best practices 
* Added security requirements developers can implement while creating an app. Now, you can deliver secure apps and keep clients safe. 
ping {names}
[DEVDOCS-3296]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3296: [update] add security best practices

---

docs/b2b-edition/specs/storefront/storefront/catalog.yaml

Update the catalog.yml to match the b2b Stoplight files
N/A
ping {names}
[DEVDOCS-5655]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5655: [update] b2b-catalog

---

docs/b2b-edition/specs/storefront/authentication.yaml

Updates to the authentication.yml file
N/A
ping {names}
[DEVDOCS-5655]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5655: [update] b2b-authentication.yml

---

docs/b2b-edition/specs/storefront/storefront/catalog.yaml

No ticket
removed br tags
n/a
ping {names}

remove <br> tags in catalog

---

docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml

Updated the sales-rep.yaml file.
N/A
ping {names}
[DEVDOCS-5655]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5655:[update] b2b-sales-rep.yml

---

reference/catalog/categories_catalog.v3.yml

* Correct category description field description
* Corrected the description of the category description field in the API docs.

Correct category description field description

---

reference/orders.v2.oas2.yml

See Slack conversation: https://bigcommerce.slack.com/archives/C57SQ401K/p1727594756996009
Fixing table
Bug Fix: fix table
ping {names}

fix-all-order-statuses-table

---

docs/b2b-edition/specs/storefront/storefront/catalog.yaml
docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml

Updating security information
n/a 
ping {names}
[DEVDOCS-5655]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated security b2b authentication details

---

reference/customers.v3.yml

changed the format of the limit callout
n/a
ping {names}
[DEVDOCS-6122]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6122: [update] change limit format

---

docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml

Moved Assign Companies to Super Admin
* 
ping {names}
[B2B-1327]: https://bigcommercecloud.atlassian.net/browse/B2B-1327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

moved assign companies to super admin to SSOT

---

docs/b2b-edition/specs/storefront/authentication.yaml
docs/b2b-edition/specs/storefront/storefront/catalog.yaml
docs/b2b-edition/specs/storefront/storefront/company.yaml
docs/b2b-edition/specs/storefront/storefront/order.yaml
docs/b2b-edition/specs/storefront/storefront/quote.yaml
docs/b2b-edition/specs/storefront/storefront/shopping.yaml
docs/b2b-edition/specs/storefront/storefront/store-config.yaml
docs/b2b-edition/specs/storefront/storefront/store.yaml

Fixed errors displayed in Visual Studio
* 
ping {names}
[B2B-1327]: https://bigcommercecloud.atlassian.net/browse/B2B-1327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2b 1327 resolve errors 

---

docs/b2b-edition/specs/api-v3/address/address.yaml
docs/b2b-edition/specs/api-v3/authentication.yaml
docs/b2b-edition/specs/api-v3/company/company.yaml
docs/b2b-edition/specs/api-v3/invoice_management/invoice/invoice.yaml
docs/b2b-edition/specs/api-v3/invoice_management/payment/payment.yaml
docs/b2b-edition/specs/api-v3/invoice_management/receipt/receipt.yaml
docs/b2b-edition/specs/api-v3/order/order.yaml
docs/b2b-edition/specs/api-v3/payment/payment.yaml
docs/b2b-edition/specs/api-v3/quote/quote.yaml
docs/b2b-edition/specs/api-v3/sales_staff/sales_staff.yaml
docs/b2b-edition/specs/api-v3/shopping_list/shopping_list.yaml
docs/b2b-edition/specs/api-v3/super_admin/super_admin.yaml
docs/b2b-edition/specs/api-v3/task/task.yaml
docs/b2b-edition/specs/api-v3/user/user.yaml

Fixed linter errors
Outstanding questions :
user.yaml - there is an error on lines 902 and 911 due to the '{field name}' requirement object
invoice_management > invoice.yaml - Need array objects for `customerFields` and `customFields`
invoice_management > payment.yaml - Need array objects for `fees`
NOTE: In invoice_management > payment.yaml , on line 162, for the data object. I changed the field name to lineItems. I hope this is correct.
* 
ping {names}
[B2B-1327]: https://bigcommercecloud.atlassian.net/browse/B2B-1327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2b 1327 s2s endpoints

---

docs/b2b-edition/models/invoice_portal/invoice.yaml
docs/b2b-edition/specs/api-v3/invoice_management/invoice/invoice.yaml
docs/b2b-edition/specs/api-v3/invoice_management/payment/payment.yaml
docs/b2b-edition/specs/api-v3/user/user.yaml
docs/b2b-edition/specs/storefront/storefront/catalog.yaml
docs/b2b-edition/specs/storefront/storefront/company.yaml
docs/b2b-edition/specs/storefront/storefront/order.yaml
docs/b2b-edition/specs/storefront/storefront/quote.yaml
docs/b2b-edition/specs/storefront/storefront/rfq.yaml
docs/b2b-edition/specs/storefront/storefront/store.yaml

These changes are far away in PR [578](https://github.com/bigcommerce/docs/pull/578) and [580](https://github.com/bigcommerce/docs/pull/580), they were accidentally deleted, and resubmit in this PR
* add some missing object properties
* add missing response
N/A
N/A
[B2B-1354]: https://bigcommercecloud.atlassian.net/browse/B2B-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2b-1354: [update] add missing objects and response

---

docs/store-operations/segments/overview.mdx
docs/store-operations/segments/promotions-api.mdx
docs/store-operations/segments/user-guide.mdx

Changed advanced editor to standard editor
* 
ping {names}
[KB-19327]: https://bigcommercecloud.atlassian.net/browse/KB-19327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

change advanced editor to standard editor

---

reference/carts.v3.yml
reference/store_information.v2.yml

fix rendering of table
n/a
Examples:
* The newly-released [X feature] is now available to use. Now, you’ll be able to [perform Y action].
* We're happy to announce [X feature], which can help you  [perform Y action].
* [X feature] helps you to create [Y response] using the [Z query parameter]. Now, you can deliver [ex, localized shopping experiences for your customers].
* Fixed a bug in the [X endpoint]. Now the [Y field] will appear when you click [Z option]. -->
* 
ping {names}

fix rendering of table in permission_set description

---

docs/b2b-edition/specs/storefront/storefront/catalog.yaml
docs/b2b-edition/specs/storefront/storefront/company.yaml

Performing final review
Catalog:
Updated to display required fields for Search Variant SKU fields
Company:
Added missing periods
* 
ping {names}
[B2B-1354]: https://bigcommercecloud.atlassian.net/browse/B2B-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B Storefront review

---

docs/b2b-edition/models/address/address.yaml
docs/b2b-edition/models/company/company.yaml
docs/b2b-edition/models/company/company_base.yaml
docs/b2b-edition/models/utils/response-413.yaml
docs/b2b-edition/specs/api-v3/address/address.yaml
docs/b2b-edition/specs/api-v3/channel/channel.yaml
docs/b2b-edition/specs/api-v3/company/company.yaml
docs/b2b-edition/specs/api-v3/invoice_management/invoice/invoice.yaml
docs/b2b-edition/specs/api-v3/order/order.yaml
docs/b2b-edition/specs/api-v3/payment/payment.yaml
docs/b2b-edition/specs/api-v3/quote/quote.yaml
docs/b2b-edition/specs/api-v3/shopping_list/shopping_list.yaml
docs/b2b-edition/specs/api-v3/super_admin/super_admin.yaml
docs/b2b-edition/specs/api-v3/task/task.yaml
docs/b2b-edition/specs/api-v3/user/user.yaml

Performing final review
* changed BC to BigCommerce
* fixed spelling of first
* changed id to ID
* changed b2b to B2B
* Fixed itemized list
* 
ping {names}
[B2B-1354]: https://bigcommercecloud.atlassian.net/browse/B2B-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B Management review

---

docs/b2b-edition/specs/api-v3/address/address.yaml

resolve indentation error in addresses.yaml
n/a
* 
ping {names}

Update address.yaml - fix linter error

---

docs/b2b-edition/specs/api-v3/address/address.yaml
docs/b2b-edition/specs/api-v3/authentication.yaml
docs/b2b-edition/specs/api-v3/channel/channel.yaml
docs/b2b-edition/specs/api-v3/company/company.yaml
docs/b2b-edition/specs/api-v3/invoice_management/invoice/invoice.yaml
docs/b2b-edition/specs/api-v3/invoice_management/receipt/receipt.yaml
docs/b2b-edition/specs/api-v3/order/order.yaml
docs/b2b-edition/specs/api-v3/payment/payment.yaml
docs/b2b-edition/specs/api-v3/quote/quote.yaml
docs/b2b-edition/specs/api-v3/shopping_list/shopping_list.yaml
docs/b2b-edition/specs/api-v3/super_admin/super_admin.yaml
docs/b2b-edition/specs/api-v3/user/user.yaml
docs/b2b-edition/specs/storefront/authentication.yaml
docs/b2b-edition/specs/storefront/storefront/company.yaml

Making endpoint names consistent, changing them all to title case 
n/a
* 
ping {names}

Update authentication.yaml - change to title case

---

docs/integrations/apps/unified-billing/index.mdx

Remove reference to beta in UB docs

---

reference/store_content.v2.yml

Add the following note: Updating the channel ID for a page is not supported.
* 
ping {names}
[DEVDOCS-5165]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5165: [update] add note about channel ID

---

reference/redirects.v3.yml

Added id:max and id:min 
Added new filters for the Get Redirects endpoint. 
* 
ping {names}
[DEVDOCS-5956]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5956: [update] added id:max and id:min

---

reference/marketing.v2.yml

Corrected "purchase_date" and "expiry_date" response body formats
Bug Fix
* 
ping {names}
[DEVDOCS-6036]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6036: [update] update date format

---

reference/orders.v2.oas2.yml

Add order_pickup_method_id field
* 
ping {names}
[DEVDOCS-5940]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5940: [update] add order_pickup_method_id field

---

docs/storefront/headless/index.mdx

Removes legacy headless resources that are not as relevant anymore
* 
* 
ping {names}

Simplify headless index

---

docs/store-operations/orders/invoice-templates.mdx

Re-ordered sections
n/a
* 
ping {names}
[DEVDOCS-5893]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5893: [update] re-order sections

---

docs/b2b-edition/specs/api-v3/authentication.yaml

Change tag from "auth" to "authentication"
* 
* 
ping {names}

fix-b2b-auth-tags

---

docs/b2b-edition/specs/api-v3/authentication.yaml

changing tag from Authentication to Auth
* 
n/a
* 
ping {names}

Update authentication.yaml -changing tags

---

reference/shipping.v3.yml

- Added api docs for v3 shipping checkout settings (`shipping/settings` endpoint)
API request and response with `Get` and `Post`:
https://github.com/user-attachments/assets/78f24e8f-cc40-458b-a911-a7fecb565b9b
ping @bigcommerce/team-shipping @bc-andreadao 
[SHIPPING-3163]: https://bigcommercecloud.atlassian.net/browse/SHIPPING-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(shipping): SHIPPING-3163 Add documentation for checkout settings endpoint

---

reference/catalog/products_catalog.v3.yml

Update the Create a Product image endpoint.
Bug Fix: Fixed the request body and the duplication
* 
ping {names}
[DEVDOCS-6129]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update create a product image request body

---

SECURITY.md

* Adding SECURITY.md
Adding file so that security researchers knows where to report if a vulnerability was found on this repository.
[APPSEC-705]: https://bigcommercecloud.atlassian.net/browse/APPSEC-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(security): APPSEC-705 Add SECURITY.md

---

docs/storefront/stencil/themes/context/handlebars-reference.mdx

#628 
* Added documentation for multiConcat handlebar helper.
* Added documentation surrounding the multiConcat handlebar helper.
N/A
ping @bc-luke @bc-vincent-zhao @bc-traciporter @bc-tgomez

docs(handlebars): Add multiConcat helper to Handlebars reference

---

reference/orders.v2.oas2.yml

Added a note that `total_sold` on products in the imported orders will remain unaffected if  external_source value is M-MIG.
Enhancement:
Specified that total_sold on products in the imported orders will remain unaffected if  external_source value is M-MIG.
* 
ping {names}
[DEVDOCS-5587]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5587: [update] add note for external_source

---

docs/storefront/stencil/cli/install.mdx

Update with the new nvm version
Updated the required node and npm versions for installing Stencil CLI.
* 
ping {names}
[DEVDOCS-6145]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6145: [update] replace nvm 18.15.0 with 20.16.0

---

docs/storefront/headless/channels.mdx
reference/settings.v3.yml

Add www settings info to configuring headless channels checkout section in dev docs
Enhancement: 
* 
ping {names}
[DEVDOCS-6143]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6143: [update] add www settings info

---

docs/store-operations/emails/object-reference/combined-order-status.yml

Added new fields to the combined order status email schema file.
Updated the Combined order status schema.
* 
ping {names}
[DEVDOCS-6147]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add new fields per DEVDOCS-6147

---

reference/customers.v3.yml

Added concurrency rate limits to 3.
Enhancement: Added concurrency rate limits to Update Customers and Upsert Customer attribute values endpoint
.
* 
ping {names}
[DEVDOCS-6122]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6122: [update] change limit from 10 to 3

---

reference/settings.v3.yml

added links to each section
* 
ping {names}
[DEVDOCS-6026]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6026: [update] add links to each section

---

docs/start/about/index.mdx

Make token name consistent throughout the docs
n/a
* 
ping {names}

Use capital letters for token

---

docs/b2b-edition/specs/api-v3/quote/quote.yaml

Changed company ID to company name as the quote list endpoint filters by company name, not ID.
Bug Fix: Changed company ID to company name in the company parameter description as the quote list endpoint filters by company name, not ID.
* 
ping {names}
[DEVDOCS-6092]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6092: [UPDATE] change company ID to company name

---

docs/b2b-edition/specs/api-v3/authentication.yaml

Added a note about the admin role to alleviate confusion.
Enhancement: Added a note about the admin role being the only role that can create tokens.
* 
ping {names}
[DEVDOCS-6107]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6107: [update] add note regarding Admin role

---

docs/store-operations/emails/object-reference/order-ready-for-pickup.yml

Fixed linter errors
n/a
* 
ping {names}

fix linter errors

---

reference/catalog/categories_catalog.v3.yml

added limits
See [PR 649](https://github.com/bigcommerce/docs/pull/649)
* 
ping {names}
[DEVDOCS-6148]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6148: [update] add limits

---

docs/b2b-edition/stencil.mdx

Corrected the path for global.js. Actual file path is `assets/js/theme/global.js`
Bug Fix:
Corrected the global.js file path in the Customizing display text section of B2B Edition for Stencil.
* 
ping {names}
[DEVDOCS-6012]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6012: [update] correct path for global.js

---

reference/checkouts.sf.yml
reference/orders.sf.yml

Updated the listPrice definition
Enhancement: Updated the listPrice definition.
* 
ping {names}
[DEVDOCS-5978]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5978: [update] listPrice definition

---

reference/orders.v2.oas2.yml

* Added accepted parameters for Orders count method
* Added accepted parameters for Orders count method
* Note that some of these parameters are irrelevant to this method and will be ignored (e.g. `limit` and `page`)
* Could be partially blocked by ORDERS-6007 (issue with `is_deleted` param not showing up on devdoc frontend)
[DEVDOCS-6013]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6013 Document supported parameters for Order Count method

---

reference/orders.v2.oas2.yml

removed enums for payment_method
* 
ping {names}
[DEVDOCS-6014]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6014: [update] remove payment_method enums

---

reference/carts.v3.yml

Added additional updates to this note
Enhancement
* 
ping {names}
[DEVDOCS-4187]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4187: [update] list_price description

---

docs/store-operations/catalog/index.mdx

Remove supported types callout
* 
ping {names}
[DEVDOCS-6156]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6156: [update] remove supported types modal

---

docs/b2b-edition/specs/api-v3/shopping_list/shopping_list.yaml

Required tags are needed to bring attention that a query parameter is needed in the Get Shopping Lists endpoint.
Enhancement: Added required tags to clarify that either a userId or a customerId is needed to run the Get Shopping Lists query.
* 
ping {names}

Feedback: [update] add required tags for query params

---

reference/widgets.v3.yml

Updated the description of key to prevent confusion
Enhancement
* 
ping {names}
[DEVDOCS-6158]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6158: [update] update key description

---

docs/start/authentication/graphql-storefront.mdx

Added in information on assigning a cart to a customer.
* 
ping {names}
[DEVDOCS-6076]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6076: [update] add guest customer login option

---

reference/catalog/products_catalog.v3.yml

* Copyedit channels response schema description for Catalog API
* Uses the suggestion from @kristinapototska in [PR 690](https://github.com/bigcommerce/docs/pull/690#pullrequestreview-2481508659)
see [PR 690](https://github.com/bigcommerce/docs/pull/690)

Copyedit channels response schema description for Catalog API

---

reference/tax_provider.yml

* More detail around our enforced expectations for tax exempt items.
[TAX-2052]: https://bigcommercecloud.atlassian.net/browse/TAX-2052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update tax provider API documentation to specify expectations for tax exempt items in equivalent response item.

---

docs/b2b-edition/specs/api-v3/authentication.yaml

Add a new parameter CustomerAccessToken in the b2b io/auth/customers/storefront endpoint.
Enhancement: Added an optional parameter to the storefront authentication endpoint for b2b.
<!-- Provide an entry for the release notes using simple, conversational language. Don't be too technical. Explain how the change will benefit the merchant and link to the feature.
NA
ping {names}

Add CAT param to b2b auth storefront endpoint

---

reference/carts.sf.yml

Removed incorrect required label
Bug Fix
* 
ping {names}
[DEVDOCS-6162]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6162: [UPDATE] remove required variant ID

---

docs/storefront/headless/index.mdx

Updated guidance so it's clear which steps to take
No update needed, this is a rewrite of existing functionality

Update trusted proxy docs

---

reference/catalog/products_catalog.v3.yml

Updated SKU description 
Clarified SKU description 
* 
ping {names}
[DEVDOCS-6161]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6161: [update] updated SKU description

---

docs/store-operations/catalog/index.mdx
reference/catalog/product-modifiers_catalog.v3.yml

Updated request to add a price adjuster
Bug Fix
* 
ping {names}
[DEVDOCS-5908]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5908: [update] update request to add a price adjuster

---

reference/customers.v3.yml

Changed max characters from 255 to 250. See slack conversation: https://bigcommerce.slack.com/archives/C071LJPGX/p1734045938059749?thread_ts=1734026915.667309&cid=C071LJPGX
* 
* 
ping {names}

email-max-characters

---

docs/storefront/stencil/cli/options-and-commands.mdx
docs/storefront/stencil/deployment/performance-optimization.mdx

* add new stencil-cli options to bundle and push
* add new section on theme optimization on source maps
Tools that provide automatic error reporting, session playback, and optimization suggestions can rely on source maps to give more readable insight. This update adds additional options to stencil-cli to optimize your themes performance with such tools.
ping @bc-traciporter

DEVDOCS-0000: [update] Add new stencil-cli options

---

reference/checkouts.sf.yml
reference/checkouts.v3.yml

v3 checkout api:
- ~~Create Fee~~ (see "Updates after change to bulk APIs")
- ~~Update Fee~~ (see "Updates after change to bulk APIs")
- ~~Delete Fee~~ (see "Updates after change to bulk APIs")
- response of checkout object added applied fees (fees:)
storefront checkout api:
- response of checkout object added applied fees (fees:)
-----
<details open>
<summary> <h3> Updates after change to bulk APIs, 2024-11-28 </h3> </summary>
on commit: https://github.com/bigcommerce/docs/pull/642/commits/5dd480c9c0107b6b6df0c5e735630fb2376222b9
v3 checkout api changes:
Have 3 endpoints to support bulk operations on fees:
- POST v3/checkouts/:checkoutId/fees
- PUT v3/checkouts/:checkoutId/fees
- DELETE v3/checkouts/:checkoutId/fees
Removed 2 endpoints:
- PUT v3/checkouts/:checkoutId/fees/:feeId
- DELETE …

doc(checkout): CHECKOUT-8739 update doc to reflect new feature of order level fees.

---

docs/store-operations/payments/index.mdx

Reverts bigcommerce/docs#712
Rolling back the change until tomorrow.

Revert "DEVDOCS-4028"

---

docs/storefront/cart-checkout/guide/add-to-cart-url.mdx

Added a note that a product identifier of some sort (such as product ID or SKU) must be included in the URL for it to be valid. 
Enhancement
* 
ping {names}
[DEVDOCS-6174]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6174: [update] add note about product_id

---

reference/promotions.v3.yml

- Include docs for cursor based pagination support for "Get Coupon Codes"
* Updated openapi schema for "Get Coupon Codes" to include pagination query parameters and new `cursor_pagination` response meta data
* "Get Coupon Codes" now supports cursor based pagination for improved query performance. Click [here](https://developer.bigcommerce.com/docs/rest-management/promotions/coupon-codes-bulk#get-coupon-codes) for details on how to implement cursor based pagination for your integrations.
Preview of api docs:
ping @bigcommerce/team-promotions @bc-jwk
[PROMO-1099]: https://bigcommercecloud.atlassian.net/browse/PROMO-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[promotions][Get Coupon Codes] Add openapi schema for cursor based pagination

---

reference/checkouts.sf.yml

Fix the rendering of :
- For Shipping Consignment
- For Pickup Consignment 
* 
ping {names}
[DEVDOCS-6177]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6177: [update] fix rendering

---

reference/checkouts.sf.yml

Added an extra line to test the rendering of an itemized list.
* 
ping {names}

Update checkouts - test the rendering of a numbered list

---

docs/b2b-edition/specs/api-v3/quote/quote.yaml
docs/b2b-edition/specs/api-v3/user/user.yaml

In the B2B App, the quote extra fields have been migrated to the unified extra fields module, so the related documentation also needs to be updated.
The modifications in this PR include:
* Change "value" to "fieldValue".
* The endpoint for getting quote extra fields configs supports pagination.
* Modify the response structure of quote extra fields.
N/A
[B2B-1437]: https://bigcommercecloud.atlassian.net/browse/B2B-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B-1437: [UPDATE] quote extra fields

---

docs/storefront/cart-checkout/metafields.mdx

Updated the platform limits for cart metafields
Enhancement:
* 
ping {names}
[DEVDOCS-6187]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6187: [update] update platform limits

---

docs/integrations/apps/unified-billing/index.mdx

Updates link in UB overview from staging -> prod

updates link in UB overview

---

docs/storefront/widgets/index.mdx

* Updated widget per store limit from 10,000 to 100,000
* Bug fix - Updated widget per store limit from 10,000 to 100,000
[DEVDOCS-5883]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5883: [Update] - Updated widget per store limit

---

docs/store-operations/catalog/msf-international-enhancements/msf-international-enhancements.mdx

Fix broken link from https://github.com/bigcommerce/docs/pull/752

MSF Int Enhancements- Fix Broken Links

---

reference/orders.v2.oas2.yml

* 
Add documentation on temporary `consignment_structure` parameter to help manage breaking change.
* 
[DEVDOCS-6194]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc(orders): DEVDOCS-6194 add docs for consignment_structure query param

---

docs/store-operations/promotions/index.mdx
docs/store-operations/promotions/multi-currency.mdx

Removed links to single schemas
* 
ping {names}
[DEVDOCS-5941]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5941: [update] remove schema links

---

reference/customers.v3.yml

See slack message: https://bigcommerce.slack.com/archives/C57SQ401K/p1737644401923599
Changed 
* "Get Customer Metafields List" to "Get a Customer Metafield"
* "Delete Customer Metafields" to Delete a Customer Metafield"
n/a
* 
ping {names}

No TICKET: [update] rename Get Customer Metafields List to Get a Customer Metafield

---

docs/integrations/apps/unified-billing/index.mdx

* Added requirement for signing UB addendum.
* Updated Unified Billing documentation to call out the required signing of the Unified Billing addendum in the partner portal.
ping @bc-traciporter @bc-terra @knowakowski 
[DEVDOCS-6084]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6084 [Update] - Added UB addendum requirement

---

docs/store-operations/customers/index.mdx

Add a link to customer examples

---

docs/storefront/graphql/index.mdx

* 
* 
ping {names}
[DEVDOCS-4923]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4923: [update] add bi-directional pagination

---

docs/integrations/apps/unified-billing/index.mdx

* Added Requirements and limitations section and included link to Help Center article.
* * Added Requirements and limitations section and included link to Help Center article "Unified Billing for Partners".
ping {names}
@bc-traciporter @bc-terra @knowakowski 
[DEVDOCS-6140]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6140 [update] - Added UB requirements and limitations

---

reference/customers.v3.yml

Fix table rendering described in Issue-765
* 
ping {names}

Issue-765: [update] fix table rendering

---

reference/customers.v3.yml

Changed "Inupt" to "Input"
* 
ping {names}

correct misspelling of Input

---

reference/webhooks.v3.yml

Update webhooks yaml file 
* Removed pagination from the meta object for [POST a Hook](https://developer.bigcommerce.com/docs/webhooks/webhooks/manage-webhooks-bulk#create-a-webhook), [GET a Hook](https://developer.bigcommerce.com/docs/webhooks/webhooks/manage-webhooks-single#get-a-webhook), [PUT a Hook](https://developer.bigcommerce.com/docs/webhooks/webhooks/manage-webhooks-single#update-a-webhook), [DELETE a Hook](https://developer.bigcommerce.com/docs/webhooks/webhooks/manage-webhooks-single#delete-a-webhook).
* Updated the order of the response body for /hooks endpoints
* Removed the 400 error response from the Get endpoints.
* Changed `store/order/*` to `store/order/created` in the examples
* 
ping {names}
[DEVDOCS-6049]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6049?atl …

DEVDOCS-6049: [update] webhook yaml file

---

docs/storefront/stencil/themes/templates/dynamic-rendering.mdx

Added new section 
* 
ping {names}
[DEVDOCS-6200]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6200: [update] add handlebars partial blocks

---

docs/start/authentication/api-accounts.mdx
docs/start/authentication/index.mdx

Reordered sections in API Accounts & OAuth Scopes
* 
ping {names}
[DEVDOCS-4269]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4269: [update] reorder sections

---

docs/storefront/widgets/guide/graphql-templates.mdx

Update link for a list of accepted `template_file` values
Bug Fix: Corrected link
* 
ping {names}
[DEVDOCS-5320]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5320: [update] update link for template_files

---

docs/storefront/stencil/themes/context/handlebars-reference.mdx

added missing handlebar helper
* 
added missing handlebar helper
* 
ping {names}

Issue-726: [update] added getImageSrcset1x2x to the list of Handlebars Helpers

---

reference/email_templates.v3.yml

Removed the note from the Get email templates endpoint
* 
* 
ping {names}
[DEVDOCS-6218]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6218: [update] remove Get email templates note

---

docs/store-operations/orders/index.mdx

Reordered the Creating order shipments and Changing order status sections in the Orders Overview article as indicated in [Issue-589](https://github.com/bigcommerce/docs/issues/589).
* 
ping {names}
[DEVDOCS-6225]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6225: [update] reorder sections

---

docs/integrations/apps/unified-billing/index.mdx

* Added Under Review to unpublished visibility status.
* Updated text of $0 checkout callout.
* Added Under Review to unpublished visibility status.
* Updated text of $0 checkout callout.
ping @knowakowski @bc-terra @bc-traciporter

DEVDOCS-6206 - [update] - UB test info update

---

docs/store-operations/settings/locales.mdx

* Fix incorrect query example for locales
cc @kristinapototska

fix incorrect query example 

---

docs/integrations/webhooks/tutorial.mdx

Update tutorial.mdx: [update] fix link

---

reference/segments.v3.yml

Added a note to the [Get All Shopper Profiles in a Segment](https://developer.bigcommerce.com/docs/rest-management/customer-segmentation/shopper-profiles-for-a-segment#get-all-shopper-profiles-in-a-segment) endpoint.
* 
ping {names}
[DEVDOCS-6229]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6229: [update] added a note

---

reference/pricing.sf.yml

Updated the description for the Get Prices endpoint.
* 
The rounded prices in the Get Prices endpoint response will align with the currency's decimal precision as defined in the [currency](https://support.bigcommerce.com/s/article/Managing-Currencies?language=en_US#add) settings page.
* 
ping {names}
[DEVDOCS-6223]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6223: [update] currency-based price rounding

---

reference/checkouts.v3.yml

Add a note regarding the Try It panel for the Delete order level fees from checkout 
* 
ping {names}
[DEVDOCS-6202]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6202:[update] added a note regarding Try It panel

---

docs/storefront/stencil/cli/options-and-commands.mdx

Table did not render correctly 
* 
ping {names}

fix stencil push table

---

reference/orders.v3.yml

See Slack conversation: https://bigcommerce.slack.com/archives/C57SQ401K/p1740609936585519
* 
ping {names}

fix typo in date_created:min

---

docs/storefront/headless/routes.mdx

* 
* 
ping {names}
[DEVDOCS-5007]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

removed extra lines in the example queries

---

docs/integrations/apps/unified-billing/postman-collection.mdx

* Updated the unified billing postman collection 
* Updated the unified billing postman collection 
* 
ping {names}
[DEVDOCS-6037]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6037: [UPDATE] updated Postman collection

---

docs/integrations/apps/unified-billing/example-queries.mdx

https://bigcommercecloud.atlassian.net/browse/BRP-17444
* updated mentions of `entityId` to the global `id`
* updated examples to show how the global id is supposed to be used
* Updated references of `entityId` to `id`. This matches the use of `id` everywhere else on the platform
ping {names}
[BRP-17444]: https://bigcommercecloud.atlassian.net/browse/BRP-17444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(billing): BRP-17444 update entityId to global id

---

reference/catalog/products_catalog.v3.yml

Removed the variants field from the Update Products (Batch) endpoint
Removed the variants field from the Update Products (Batch) endpoint
* 
ping {names}
[DEVDOCS-6278]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6278: [update] removed variants from Update Products

---

reference/orders.v2.oas2.yml

- add defaults for pagination
- correct default for order taxes details param
* Add defaults for offset based pagination params
* Corrected default value for `details` request param
* 
[DEVDOCS-6304]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(orders): DEVDOCS-6304

---

docs/storefront/graphql/best-practices.mdx

Add a best practices article to reduce abusive behavior.
Added a best practices article to help merchants avoid 429 errors. 
* 
ping {names}
[DEVDOCS-6284]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6284: [new] add GraphQL Best Practice article

---

docs/store-operations/currencies/index.mdx

Update the image
* 
ping {names}
[DEVDOCS-6289]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update multi-currency-display-currency image

---

reference/currencies.v2.yml

Updated the currencies endpoints
- removed `date_created` and `date_modified`, replaced with `last_updated`.
- created new schemas for PUT and POST endpoints.
- added `default_for_country_codes` and `use_default_name`
- removed required for the currency_code field for the PUT request body
- updated the PUT request body
- updated the POST request body
- added readonly for the last_updated field
* 
ping {names}
[DEVDOCS-6313]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6313: [update] currencies endpoints

---

reference/currencies.v2.yml

Move required fields from the Update a currency endpoint
* 
ping {names}
[DEVDOCS-6313]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

remove required field for Update a currency endpoint

---

docs/storefront/headless/channels.mdx

Added best practices information to the Creating Channels article
* 
ping {names}
[DEVDOCS-6106]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6106: [update] add channel best practices

---

docs/storefront/cart-checkout/open-checkouts/guide.mdx

Made updates per JIRA ticket
* 
ping {names}
[DEVDOCS-6310]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6310: [update] installing an open source checkout

---

docs/storefront/stencil/themes/context/object-reference/config.yml

Fix the rendering of config.json
* 
ping {names}

Issue-836: [update] fix rendering of config.json

---

reference/price_lists.v3.yml

Add cursor pagination to the following endpoints
- GET /v3/pricelists
- GET /v3/pricelists/{id}/records
- GET /v3/pricelists/assignments
* 
ping {names}
[DEVDOCS-6312]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6312: [update] add cursor pagination

---

docs/integrations/apps/guide/SDK.mdx
docs/integrations/apps/guide/best-practices.mdx

* 
* 
ping {names}
[DEVDOCS-4374]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4374: [update] manage user session timeouts

---

docs/storefront/stencil/themes/foundations/react.mdx

Updated Using npm and React to Customize Your Theme for React 18
* 
replaces #872 
[DEVDOCS-5651]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5651: [update] for React 18

---

docs/storefront/cart-checkout/guide/graphql-storefront.mdx

Replaced url with path
* 
ping {names}
[DEVDOCS-6269]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6269: [update] replace url with path

---

docs/b2b-edition/specs/storefront/storefront/company.yaml

* Company, Address, and User endpoints for B2B Storefront are updated with new descriptions and data.
* As part of the ongoing B2B content refresh, we've updated the storefront Company, Address, and User endpoints to include all core data and more descriptive explanations of fields, parameters, request bodies, and responses.
ping {bc-vince}
[DEVDOCS-6236]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

B2B Refresh - Storefront Companies

---

docs/integrations/apps/guide/catalyst-compatible-apps.mdx

fix formatting

---

docs/start/authentication/graphql-storefront.mdx

Added error message
* 
ping {names}
[DEVDOCS-6342]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6342: [update] add error message

---

docs/storefront/stencil/themes/context/handlebars-reference.mdx

applied style guide

---

reference/channels.v3.yml

Added `is_enabled` to the channels endpoints
* 
ping {names}
[DEVDOCS-6337]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6337: [update] added is_enabled to channels

---

docs/store-operations/translations/categories.mdx
docs/store-operations/translations/index.mdx

#NO Ticket
Enhancements and updating host with `https://api.bigcommerce.com/`
* 
ping {names}

Translations Updates

---

docs/storefront/cart-checkout/open-checkouts/guide.mdx

Update node version
* 
ping {names}
[DEVDOCS-6356]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6356: [update] version node

---

docs/b2b-edition/specs/api-v3/company/company.yaml

- Tested and provided general examples of formatting.
- Included example of a `null` valued field
* 
* Clarified the extraFields parameter and its usage in Get All Companies
ping { @bc-Vince }
[DEVDOCS-6344]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6344 - Clarify extraFields parameter

---

docs/integrations/tax.mdx

* Adjust guidance around platform wide availability for tax providers.
This generally causes confusion and extra, unnecessary communication cycles. This option requires a separate process, and (most importantly) a business arrangement, and hence shouldn’t be part of the initial development information requirements.
- Adjusted platform-wide availability documentation to describe a separate development application process.

Adjust platform wide availability guidance

---

docs/b2b-edition/specs/storefront/storefront/store.yaml

- Restructured doc for readability
- Added descriptions for endpoints, parameters and fields
- Clarified usage expectations
- Added new expected response with explanation
* 
* 
ping { @bc-Vince @CNanninga }
[DEVDOCS-6240]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6240 - Store Settings (SF) refresh

---

docs/b2b-edition/specs/api-v3/sales_staff/sales_staff.yaml

- Restructured doc for readability.
- Added descriptive content to endpoints, parameters, and fields.
- Clarified and corrected responses.
* 
* 
ping { @bc-Vince @CNanninga }
[DEVDOCS-6247]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6247 - Content Refresh S2S Sales Staff

---

docs/storefront/headless/products/faceted-textual-search.mdx

- Reorganize and enhance documentation for faceted and textual search in the GraphQL Storefront API
- Add comprehensive examples of AND/OR logic for category-based product filtering
- Include detailed explanation of product attribute filtering with code examples
- Add limitations and recommendations section with practical workarounds
We've revamped our GraphQL Storefront API search documentation to make implementing faceted and textual search easier than ever. The enhanced documentation provides clearer examples, explains filtering logic options, and includes practical recommendations to help you build powerful product search experiences for your headless storefront. Whether you're displaying filtered category pages, implementing search with facets, or creating complex filter …

docs(search): ES-5590 Add GQL Search improved feature ES-5244

---

docs/b2b-edition/best-practices.mdx

Removed specific concurrent call limits
Added B2B-specific recommendations
Added list of general API best practices
* Added introduction will bullet list of best practice resources
* Added link to release notes when discussing integration updates
* Added standard API rate limit and called out endpoint-specific limits
* Removed outdated concurrency limit
* Added section on webhooks
Examples:
* As part of our ongoing content refresh for B2B Edition developer documentation, we have expanded the information on best practices for using B2B Edition's APIs. This includes:
* Adding a list of resources for general best practices
* Providing more detailed information on API rate limits
* Adding information on webhooks
[DEVDOCS-6255]: …

DEVDOCS-6255 - Content Refresh - "Best Practices"

---

docs/integrations/apps/guide/catalyst-compatible-apps.mdx

* Updating the section "How will users know my app is Catalyst-compatible?" with the finalized process, and to reflect the redesigned Dev Portal.
* Updated process on submitting apps to review for Catalyst compatibility.
@bc-terra @bc-traciporter 
[DEVDOCS-6285]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6285 | App Marketplace - Catalyst Compatible App Badges

---

docs/b2b-edition/specs/storefront/storefront/sales-rep.yaml

- Restructured doc for readability.
- Included known error messages on GET requests.
- Added descriptive content for endpoints, parameters, and fields
* 
* 
ping { @bc-Vince @CNanninga }
[DEVDOCS-6238]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6238 - Content Refresh - SF Super Admin

---

docs/storefront/graphql/index.mdx

- A project is in the works to allow price-based sorting that uses price lists, but the function is not available currently.
* There's a known issue in price-based sorting using GraphQL. While there is a project to remedy the behaviour, it is lower priority.
* We've added messaging to indicate the the behaviour.
* A known issue in price-based sorting has been called out in our GraphQL documentation.
ping {names}
[DEVDOCS-6384]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6384 - Add alert about price-based sorting

---

docs/b2b-edition/specs/storefront/storefront/rfq.yaml

Removed callout formatting to resolve CircleCI issue; this is a revision to solve an error that prevented the full merge of PR 902.

DEVDOCS-6237 | Content Refresh - "Rfq" (Storefront)

---

docs/storefront/headless/products/faceted-textual-search.mdx

* Clarification on how filtering by disabled filters can potentially malfunction or change without further notice
*  This is just a quick: when merchants rely on filtering by disabled filters, there’s no guarantee that behavior will remain consistent. Since these filters are not marked as enabled, any changes to the filtering engine, facets logic, or performance optimizations can cause these filters to silently break, malfunction, or disappear from results — without any prior notice.
In short, depending on disabled filters is relying on undefined behavior — and that makes the implementation fragile by design.
ping {@bc-terra}

docs(search): ES-5682 - Clarify filtering by attributes behavior

---

reference/promotions.v3.yml

* Add new parameter for list promotions endpoint
ping @bigcommerce/team-promotions 
[DEVDOCS-6412]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(promotions): DEVDOCS-6412 add list promotions "query" request param

---

docs/integrations/apps/unified-billing/example-queries.mdx
docs/integrations/apps/unified-billing/index.mdx

* Added a App Partners Responsibilities section to the UB Overview page.
* Added trial behavior explanation under the example Create a Checkout section to better describe to app partners how to utilize them.
* Added trial behavior explanation under the example Cancel a Subscription section to better describe to app partners how they work for cancellations. 
* 
ping {names}
[BRP-17658]: https://bigcommercecloud.atlassian.net/browse/BRP-17658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BRP-17658 Add UB trials docs

---

reference/orders.v2.oas2.yml

Merchants found it ambiguous if date is for the first shipment of the order or when the order is fully shipped.
Updated description to confirm date if for when the order is fully shipped.
* 
ping @bigcommerce/team-orders @bigcommerce/team-shipping 
[DEVDOCS-6426]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(orders): DEVDOCS-6426 Update date_shipped description

---

docs/integrations/scripts.mdx

* Guidance for developing Script Manager scripts for Catalyst storefronts
https://github.com/bigcommerce/catalyst/pull/2477
https://bigcommercecloud.atlassian.net/issues/PROJECT-6959
ping @CNanninga 
[DEVDOCS-6440]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add details for writing scripts for Catalyst

---

docs/store-operations/settings/locales.mdx

Updated language to anticipate feature change
* Added note that feature availability, while only available in Catalyst at present, is expected to be expanded in the future.
* N/A
ping { @bigcommerce/dev-docs-collaborators }
[DEVDOCS-6434]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6434 - Update messaging about feature

---

docs/storefront/graphql/best-practices.mdx

Added GQL Clients to best practices section
The Best Practices section in the GraphQL docs now highlights the use of code generation for schema alignment during development.
cc @kristinapototska 
[DEVDOCS-6427]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6427 - add development best practices for GQL

---

docs/store-operations/translations/brands.mdx
docs/store-operations/translations/categories.mdx
docs/store-operations/translations/index.mdx
docs/store-operations/translations/locations.mdx

Reverts bigcommerce/docs#1023
This will not be rolled out until August 21st.

Revert "DEVDOCS-6453 - add resourceId filter to translation gql api examples"

---

docs/storefront/cart-checkout/checkout-url.mdx

https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6431
* New doc for Checkout URL
* Apps or AI agents can use the Checkout URL format to create a new cart, add products, and direct a shopper to your BigCommerce storefront’s checkout.
@bc-terra New doc for your review!
[DEVDOCS-6431]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6341 | Checkout - Enhanced Checkout URL

---

reference/orders.v2.oas2.yml

Fix some minor style issue
* remove unnecessary trailing quote
* ensure the value is string format
n/a
ping @bigcommerce/dev-docs @bigcommerce/team-orders 
[DEVDOCS-6465]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

remove end double quotes and convert type to string

---

docs/b2b-edition/specs/api-v3/payment/payment.yaml

- Verified endpoint availability and functionality
- Verified request and response bodies
- Reworked incorrect response bodies for two GET endpoints
- Implemented wide use of efficiently designed schemas
- Added descriptive copy for each endpoint, field, and paramter
* As part of our ongoing B2B Edition Docs overhaul, we've updated the Server-to-Server Payments API documentation to reflect accurate examples of each endpoint as well as descriptive copy for each feature in the doc!
ping { @CNanninga @BC-EEspinosa @bigcommerce/dev-docs-team }
[DEVDOCS-6245]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6245 - S2S Payments content refresh

---

reference/orders.v2.oas2.yml

update customer_locale description in doc
* since we support new format of customer locale validation, so update customer_locale description for the supported format in doc

ORDERS-7170 update customer_locale description in doc

---

docs/store-operations/catalog/index.mdx

* Added information about the Catalog Summary endpoint to improve visibility for the endpoint.
* We added the Catalog Summary endpoint to several new descriptive files to improve visibilty.
[DEVDOCS-6371]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6371 - Catalog Summary visibility

---

reference/store_logs.v3.yml

* Doc was missing `sort` and `direction` as parameters for the endpoint. These have been added.
* Rearranged parameter fields to be more readable.
* We've documented an existing feature previously missed in our documentation.
ping { @bigcommerce/dev-docs }
[DEVDOCS-6472]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6472 - Add sort and order parameters

---

docs/store-operations/translations/products.mdx

Removed translatable properties list from product translations documentation.
* 
* 
ping {names}
[DEVDOCS-6532]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-6532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-6532 - Remove unsupported
